MystenLabs/walrus

docs/book/walrus-sites/portal.md
docs/book/walrus-sites/tutorial-install.md

The markdown tabs are not working. I am removing them until we fix this.

docs(walrus-sites): remove non-working md tabs temporarily

---

docs/book/walrus-sites/intro.md
docs/book/walrus-sites/overview.md

- Fix the flatland overview.
- Fix the b36 resolution section in the technical overview.

docs(walrus-sites): fix walrus sites overview b36 domain mentions and flatland intro

---

scripts/simtest/simtest-run.sh

In the past few days, the simtest nightly constantly encounter watchdog timeout in simtest using the
`default_setup()`. After debugging, it is primarily due to that in those tests, we create a sui cluster in a simgle
thread and the initializatine of the the sui cluster often taking more than 5 seconds (the default watch dog timeout).
We should increase the watcdog timeout in general to account for this case.
After this PR, the nightly [is successful](https://github.com/MystenLabs/sui-operations/actions/runs/14163659039).
---
For each box you select, include information after the relevant heading that describes the impact of your …

fix: add longer watchdog timeout in nightly simtest

---

Cargo.lock
crates/walrus-service/Cargo.toml
crates/walrus-service/src/client/daemon.rs
crates/walrus-service/src/common/telemetry.rs
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_sync.rs
crates/walrus-service/src/node/server.rs
crates/walrus-test-utils/src/lib.rs
crates/walrus-utils/Cargo.toml
crates/walrus-utils/src/metrics.rs
crates/walrus-utils/src/metrics/tokio.rs

This enables the use of the `tokio-metrics` crate with the `prometheus::Registry` and instruments HTTP routes, event processing, and blob sync tasks `tokio_metrics::TaskMonitor` to record metrics for when tasks are poll slowly or are scheduled but delayed to be run due to other tasks polling slowly.
Local testbed and a unit tests
---

feat: add tokio metrics to major storage node tasks

---

setup/walrus-install.sh

Users noticed that the install script was not working correctly on certain platforms. Issue was centralized around usage of `install`. This change reverts to simpler means to achieve the same end. Issue was discussed in a [previous PR](https://github.com/MystenLabs/walrus/pull/1862). 
Manually tested.

fix: fix walrus install script for certain platforms

---

crates/walrus-service/src/node.rs
crates/walrus-service/src/node/server.rs
crates/walrus-service/src/node/server/routes.rs
crates/walrus-service/src/node/storage.rs

It was not an issue before when using std::sync::lock because there won't be any interleaving of locks. By switching to
tokio locks, now it's possible that code can yield when holding the lock.
---

fix: changing shard status query from non-blocking to wait for status is retrieved

---

crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/node/metrics.rs
crates/walrus-service/src/node/shard_sync.rs
crates/walrus-service/src/node/storage/shard.rs
crates/walrus-stress/src/generator/blob.rs

Since at the current stage, shard transfer is significantly faster than shard recovery.
---

feat: add an option that when resuming shard sync upon node restart always try shard transfer first

---

crates/walrus-service/src/node.rs
crates/walrus-service/src/node/consistency_check.rs
crates/walrus-service/src/node/dbtool.rs
crates/walrus-service/src/node/metrics.rs
crates/walrus-service/src/node/node_recovery.rs
crates/walrus-service/src/node/shard_sync.rs
crates/walrus-service/src/node/storage.rs
crates/walrus-service/src/node/storage/blob_info.rs
crates/walrus-simtest/src/test_utils.rs

Similar to #1790 , this PR implements consistency check for per object blob info table. The bulk of the implementation
is to implement an iterator over the per object blob info table.
Also turned on per object blob info consistency check in all simtest.
Contributes to WAL-701
Unit test, simtest
---

feat: per object blob info consistency check

---

crates/walrus-service/src/test_utils.rs
crates/walrus-service/src/testbed.rs
crates/walrus-sui/src/test_utils/system_setup.rs
crates/walrus-sui/tests/test_walrus_sui.rs

Batch these requests otherwise when running ad-hoc network for throughput testing, we run into congestion errors like:
```
Mar 12 22:37:48 wah-sui-sadhan3-9cfc131 google_metadata_script_runner[2171]: startup-script: 2025-03-12T22:37:48.323373Z ERROR create_storage_node_configs:register_committee_and_stake: walrus_sui::test_utils::system_setup: error=>
Mar 12 22:37:48 wah-sui-sadhan3-9cfc131 google_metadata_script_runner[2171]: startup-script: 2025-03-12T22:37:48.329682Z ERROR create_storage_node_configs: walrus_service::testbed: error=execution cancelled due to shared object c>
Mar 12 22:37:48 wah-sui-sadhan3-9cfc131 google_metadata_script_runner[2171]: startup-script: Error: execution cancelled due to shared object congestion on objects …
```

fix(test): Batch requests to register nodes to prevent congestion error

---

crates/walrus-service/src/client/error.rs
crates/walrus-sui/src/client.rs

Clarify the insufficient Sui error messages to say SUI, instead of "gas."
CI Pipeline.

fix: simplify wording for gas errors

---

crates/walrus-sui/src/utils.rs
docker/walrus-antithesis/build-test-config-image/files/deploy-walrus.sh

We need to fund enough tokens to stress client wallets. Current setup encounters not enough gas coin errors.
---

chore: stress client wallets setup in antithesis

---

crates/walrus-service/src/node/storage/shard.rs
crates/walrus-service/src/node/system_events.rs
crates/walrus-service/src/test_utils.rs

Previously, we use .as_any().downcast_ref<EventProcessor>, but the dyn EventManager can also be a Arc<EventProcessor>, depending on where the event processor is initialized. Since all the downcast was to 
convert to EventProcessor, implement as_event_processor() so that all the types implementing EventManager
can do explicit type conversion.
---

fix: explicitly cast dyn EventManager to EventProcessor ref

---

crates/walrus-service/bin/deploy.rs
scripts/local-testbed.sh

This enable running ./local-testbed.sh with a single node, and also allows providing an IP address different from 127.0.0.1.
---

feat: allow single-node local testbeds

---

crates/walrus-service/bin/deploy.rs
crates/walrus-service/bin/node.rs
crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/common/utils.rs
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_sync.rs
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/node/events/event_blob_writer.rs
crates/walrus-service/src/node/server.rs
crates/walrus-service/src/node/server/routes.rs
crates/walrus-service/src/node/storage.rs
crates/walrus-service/src/node/storage/shard.rs
scripts/local-testbed.sh

This moves two verifications to run on background threads and changes the methods that store slivers such that they use `tokio::task::spawn_blocking`.
Depends on #1893 
Refactoring, existing tests apply.
---

fix: reduce blocking on tokio core threads

---

crates/walrus-proxy/src/admin.rs
crates/walrus-proxy/src/config.rs
crates/walrus-proxy/src/consumer.rs
crates/walrus-proxy/src/handlers.rs
crates/walrus-proxy/src/main.rs

adding removing labels supports to walrus-proxy to better manage metrics cardinality
deployed to our kubernetes cluster and it worked with new config
---

feat: support removing labels in walrus-proxy

---

.github/workflows/code.yml
.pre-commit-config.yaml
crates/walrus-service/src/node/events/event_blob_writer.rs

Because we use [nextest](https://nexte.st/) to run our tests, which [doesn't support doctests](https://github.com/nextest-rs/nextest/issues/16), we didn't actually notice this. This adds doctests to CI and pre-commit (and fixes one issue that causes doctests to fail).
CI.

chore: add doctests to CI and pre-commit

---

crates/walrus-service/src/node.rs
crates/walrus-service/src/node/shard_sync.rs
crates/walrus-service/src/node/storage/shard.rs

Shard transfer is a long running process and even though it may encounter error (e.g. the source server restart),
it should continue using shard transfer as long as it can continue make progress. The shard transfer should only
switch to shard recovery if it encounters error for extended period of time without any progress.
Integration tests with specific scenario created.
---

fix: shard transfer resets timer for switching to recovery after it makes progress

---

crates/walrus-service/bin/node.rs
crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/backup/service.rs
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/events/event_blob_writer.rs
crates/walrus-service/src/node/events/event_processor.rs
crates/walrus-service/src/node/events/event_processor_runtime.rs
crates/walrus-service/src/node/storage/database_config.rs
crates/walrus-service/src/test_utils.rs

Some rocksdb instances are not configurable from db config settings. This PR allows event processor db and event blob writer dbs to be configured by user defined settings.
---

feat: Pass db config settings to event processor and blob writer dbs

---

crates/walrus-service/src/node/dbtool.rs
crates/walrus-service/src/node/events/event_processor.rs

Organize constants in event_processor in a module and import it properly.
---

refactor: Organize event processor constants in a mod

---

docs/book/usage/sdks.md

Adds a Python SDK to the list of community SDKs and adds info on Walruscan and the Awesome Walrus repo.
Look at preview. 👀

docs: extend SDKs page

---

crates/walrus-sui/src/client/retry_client.rs

Fixes an issue where we use duplicate coins in a transaction because we repeatedly fetch the same pages from the coin api.
---

fix: stop fetching pages from the coin api

---

crates/walrus-orchestrator/src/main.rs
crates/walrus-proxy/src/main.rs
crates/walrus-service/bin/backup.rs
crates/walrus-service/bin/client.rs
crates/walrus-service/bin/deploy.rs
crates/walrus-service/bin/node.rs
crates/walrus-service/src/client/cli/args.rs
crates/walrus-service/src/client/daemon/cache.rs
crates/walrus-service/src/node/dbtool.rs
crates/walrus-stress/src/main.rs
crates/walrus-sui/src/client/rpc_config.rs

Fixes #1944 
This PR updates deprecated #[clap(...)] attributes to their modern equivalents in clap 4.x.
The current codebase still uses outdated syntax that has been deprecated since version 4.0.
By making this update, we ensure compatibility with future versions and maintain code quality.
I ran cargo check --features clap/deprecated after making the changes, and the previous clap deprecation warnings are no longer present.
cargo check --features clap/deprecated

fix(cli): replace deprecated `clap` attributes with `command` or `arg`

---

crates/walrus-service/src/node.rs
crates/walrus-service/src/node/system_events.rs

This PR fixes the issue that when repositioning event cursor for a node which recovered using event blobs, we expect `EventID` to always exist. But `EventID` is only used in legacy event processor and since when creating the blobs, we do not use `EventID` it is captured as `None` in event blobs and hence it doesn't exist in event blobs. The fix is to do the same thing that we do in normal functioning of event cursor table i.e. to use a special event id when updating cursor.
Deployed it to the ptn node which was breaking, and the node is able to get past the error (but now fails because of a different but expected error):
```
Apr 09 19:47:01 mia-ptn-sto-00 walrus-node[1350683]: {"timestamp":"2025-04-09T19:47:01.030127Z","level":"INFO","fields":{"message":"open storage for existing shards …
```

fix: Use event id for checkpoint events when repositioning event cursor

---

docs/book/SUMMARY.md
docs/book/walrus-sites/routing.md
docs/book/walrus-sites/tutorial-install.md
docs/book/walrus-sites/tutorial-publish.md

- Update curl request to use the mainnet branch in the site-builder tutorial-install.
- Reduce epoch count in publish and update commands from 100 to 1 in the publishing tutorial. Apart from 100 epochs not being supported in mainnet, it's also unecessary to publish a test site for so long.
- Include metadata in the ws-resources section.
- Remove an old admonish info page about Testnet features.
Proof read.
---

docs(walrus-sites): curl request and s-b publish number of epochs

---

crates/walrus-service/src/testbed.rs

When creating config files that should be moved to a different location, we need to adjust the keyfile paths as well.
Manually run the `walrus-deploy generate-dry-run-configs` command.

fix(deploy): correctly adjust keyfile paths

---

Cargo.toml
crates/walrus-service/src/client/daemon.rs
crates/walrus-service/src/client/daemon/routes.rs
crates/walrus-service/src/node/server.rs
deny.toml

Adds CORS headers to the node endpoints, and improves the CORS header on the daemon endpoints.
Depends on #1929 , because it resolves a RUSTSEC advisory in tokio that would have otherwise been added to the `deny.toml` exceptions.
Closes WAL-748
---

fix: add CORS headers to server endponints

---

Cargo.lock
Cargo.toml
crates/checkpoint-downloader/src/downloader.rs
crates/walrus-service/src/node/events.rs
crates/walrus-service/src/node/events/event_processor.rs
crates/walrus-sui/Cargo.toml
crates/walrus-sui/src/client/retry_client.rs

This PR does two fixes:
1. Recreate the rpc client on 10 minutes worth of continuous failure. Recreating the client is similar to restarting the node
2. Allows rpc to fallback to archive using a exponentially growing window size. This allows rpc to fallback to archive after 1 minute of no success  from any endpoint
Existing tests

fix: Recreate rpc client on extended failure and fallback to archive

---

crates/walrus-sui/src/client.rs
crates/walrus-sui/src/client/read_client.rs

Reduce the usage of the WalletContext for access to Sui RPC nodes, since it lacks failover semantics. Note that RetriableSuiClient also lacks failover semantics, but we can add them in the future.
CI pipeline.

chore: leverage RetriableSuiClient for reference gas price

---

crates/checkpoint-downloader/src/downloader.rs
crates/walrus-service/src/node/events/event_processor.rs
crates/walrus-sui/src/client/retry_client.rs
docs/book/walrus-sites/tutorial-publish.md

Prepare FailoverClient for reuse by giving a name to the concept of the FailoverClient.
CI Pipeline.

chore: refactor pair into struct for failover clients

---

crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node/committee/request_futures.rs
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/test_utils.rs

As we have seen, sliver recovery is currently bottlenecked by storage nodes that are overwhelmed by recovery symbols
requests, and may take long time to return 503. This currently is suspected to be the main bottleneck of blob recovery
after all the blob recovery improvements implemented by @jpcsmith. By allowing requesting additional symbols initially,
sliver recovery saves on latency to wait for a 503 to return and create another requests.
All simtest integration tests are randomly chosen a value to request additional symbols.
---
a user might notice and …

feat: add an option to request additional symbols from the beginning during sliver recovery

---

crates/walrus-e2e-tests/tests/test_client.rs
crates/walrus-sui/src/client/read_client.rs

Allows reading a shared blob by object ID.
extended existing test
---

feat: allow looking up shared blobs by their object ID

---

crates/walrus-service/src/client/cli/args.rs
crates/walrus-service/src/client/cli/runner.rs
docs/book/usage/networks.md
docs/book/usage/setup.md

There was a bug in our code where we check for the existence of the default Sui configuration directory, which we implicitly created immediately before.
This PR also updates some related documentation.
Closes #1941. 
Manual testing:
```terminal
$ walrus generate-sui-wallet
2025-04-10T10:06:13.998079Z DEBUG walrus_service::common::utils: initialized scoped tracing subscriber
2025-04-10T10:06:14.003090Z  INFO walrus: client version: 1.21.0-1566f8114f84-dirty
2025-04-10T10:06:14.008298Z  INFO walrus_service::client::cli: using Walrus configuration from '~/.config/walrus/client_config.yaml' with 'mainnet' context
2025-04-10T10:06:14.008499Z  INFO walrus_sui::config: using Sui wallet configuration from '~/.sui/sui_config/client.yaml'
2025-04-10T10:06:14.010574Z  INFO …
```

fix(client): fixed generation of a new wallet at default path

---

crates/walrus-sdk/src/client/communication/factory.rs
crates/walrus-sdk/src/error.rs
crates/walrus-service/src/node/metrics.rs

Without this change, the panic a few lines below can be triggered in the genesis epoch (which results in a cryptic error output):
```
thread 'main' panicked at crates/walrus-service/src/client/communication/factory.rs:302:13:
internal error: entered unreachable code: `all()` guarantees at least 1 result and all results are errors
```
None.

fix(client): prevent panic in genesis epoch

---

crates/walrus-sdk/src/client.rs
crates/walrus-sdk/src/client/communication/node.rs

Converted  `NodeResult` to normal struct from tuple struct
Closes: #1224

fix(client): change `NodeResult` to normal struct from tuple struct

---

crates/walrus-service/src/node.rs
crates/walrus-simtest/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_failure.rs
crates/walrus-sui/src/types/events.rs

Certified blob's event epoch is the epoch that the blob is originally certified, not the epoch of the event generated.
This epoch can be very old if certified blob event is generated from a blob extension.
Unittest, integration test, local testbed.
---

fix: epoch shard assignment should always use node `event_epoch` rather than the epoch from the event

---

crates/walrus-service/src/node.rs
crates/walrus-simtest/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_failure.rs
crates/walrus-sui/src/types/events.rs

fix: cherry pick epoch shard assignment should always use node `event_epoch` rather than the epoch from the event

---

Cargo.lock
crates/walrus-sdk/client_config_example.yaml
crates/walrus-sdk/src/config.rs
crates/walrus-sdk/src/config/communication_config.rs
crates/walrus-service/bin/deploy.rs
crates/walrus-service/bin/node.rs
crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/backup/service.rs
crates/walrus-service/src/client/cli.rs
crates/walrus-service/src/client/cli/runner.rs
crates/walrus-service/src/client/multiplexer.rs
crates/walrus-service/src/common/config.rs
crates/walrus-service/src/common/utils.rs
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/node/events/event_processor.rs
crates/walrus-service/src/node/storage/shard.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-service/src/testbed.rs
crates/walrus-stress/Cargo.toml
crates/walrus-stress/src/generator.rs
crates/walrus-stress/src/generator/write_client.rs
crates/walrus-stress/src/main.rs
crates/walrus-sui/src/client/read_client.rs
crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs
crates/walrus-sui/src/config.rs
crates/walrus-sui/src/test_utils.rs
crates/walrus-sui/src/utils.rs
docker/walrus-antithesis/build-test-config-image/files/deploy-walrus.sh

Add a request timeout config option in ClientConfig (client side) and SuiConfig (server side) to config
the WalletContext and SuiClient request timeout communicating with Sui.
By default we are not setting it, which is the same behavior as today.
This is needed mostly for antithesis test at the moment.
---

feat: config sui client request timeout

---

mainnet-contracts/subsidies/Move.lock
mainnet-contracts/subsidies/Move.toml
mainnet-contracts/wal/Move.lock
mainnet-contracts/wal/Move.toml
mainnet-contracts/walrus/Move.lock
mainnet-contracts/walrus/Move.toml
mainnet-contracts/walrus/sources/staking/staking_inner.move

This PR makes sure that the compiler `Move.toml` and `Move.lock` files in `mainnet-contracts` reflect the state at the actual time of deployment. For the `wal` contract, this was commit 16606e7e52e3f7573cd917665a71e7caf49b0807, and for the `walrus` and `subsidies` contracts, this was commit 10217c558c110b2f9dc7bbc35b8947628b65e5e3.
In particular, the goal is to make the used compiler version clear to ensure that running `sui client verify-source` succeeds if the sui version corresponding to the compiler version in the `Move.lock` files is used. Small changes from after the deployment to e.g. comments or formatting in the source code that do not affect this have been kept intact.
There are some caveats, namely, we cannot accurately reflect the dependency versions for `wal`, since the …

fix: make mainnet-contracts/*/Move.* correspond to deployed version

---

contracts/walrus/sources/system/shared_blob.move

Added getters that return references to the `Blob` and `Balance<WAL>` in the `SharedBlob` object. Right now, smart contracts onchain have no insight into `Blob` stored within a `SharedBlob`. For example, imagine a `Table<u256, ID>` that maps a Blob ID to an ID of a `SharedBlob`. Without access to the underlying `Blob`, it's not possible to validate that Blob ID is correct.

feat: add getters to SharedBlob

---

book.toml
docs/book/blog/00_intro.md
docs/book/blog/01_announcing_walrus.md
docs/book/blog/02_devnet_update.md
docs/book/blog/03_whitepaper.md
docs/book/blog/04_testnet_update.md
docs/book/blog/05_testnet_redeployment.md

This updates or removes links in older blog posts and clarifies the corresponding warning admonitions.
Inspect preview.

docs: clean up links in old blog posts

---

CONTRIBUTING.md
docs/book/walrus-sites/builder-config.md
docs/book/walrus-sites/tutorial-install.md
docs/book/walrus-sites/tutorial-publish.md

This PR fixes multiple broken or outdated internal and external links identified via automated link checking. The following types of updates were made:
- ✅ Updated internal `.html` references to `.md` (e.g., `tutorial-install.html` → `tutorial-install.md`)
Error

docs: correctly link to MD files

---

docs/examples/javascript/README.md
docs/examples/javascript/system_stats.html

An example that reads and parses the Walrus inner system object to extract and display some data about current and future epochs.

docs: add a JS example to read the system object data

---

crates/walrus-service/Cargo.toml
crates/walrus-service/bin/client.rs
crates/walrus-service/build.rs

This embeds the build time in the binary and logs a warning at runtime if the binary is more than 30 days old.
```console
$ export RUST_LOG=warn
$ unset SOURCE_DATE_EPOCH
$ cargo run --bin walrus -- -V
Compiling walrus-service v1.23.0 (/Users/markuslegner/github/walrus/crates/walrus-service)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.68s
Running `target/debug/walrus -V`
walrus 1.23.0-22cb042e62af
$ SOURCE_DATE_EPOCH=0 cargo run --bin walrus -- -V 
Compiling walrus-service v1.23.0 (/Users/markuslegner/github/walrus/crates/walrus-service)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 6.79s
Running `target/debug/walrus -V`
2025-04-24T10:40:56.566762Z  WARN walrus: This build of the Walrus client is older than 30 days. Please update to the latest version. …
```

feat(client): log warning for old clients

---

Cargo.lock
Cargo.toml
crates/walrus-service/Cargo.toml
crates/walrus-service/bin/client.rs
crates/walrus-service/src/client/cli/args.rs
docs/book/usage/client-cli.md

Generates shell completion scripts that can be used for walrus packages. Optionally use --shell for specific shell output.
```
target/debug/walrus completion > comp
source comp
export PATH=$PATH:./target/debug
walrus <tab tab>
checked output of
target/debug/walrus completion --shell=zsh
```
---

feat(client): add `walrus completion` command

---

.github/workflows/lint.yml
.pre-commit-config.yaml
crates/walrus-service/src/testbed.rs
crates/walrus-sui/src/client/metrics.rs

- Add `--hide-inclusion-graph` to `cargo deny` in precommit to reduce the amount of output.
- Use `taiki-e/install-action` to install `licensesnip` in CI.
- Update some default values for deploying subsidies to those currently used on Mainnet.
- Remove an old Mysten Labs copyright header.

chore: combination of a few unrelated chores

---

crates/walrus-service/src/node/committee/committee_service.rs
crates/walrus-service/src/node/committee/request_futures.rs
crates/walrus-service/src/node/metrics.rs

This adds the following metrics to the recover sliver flow:
- `walrus_recovery_future_backoff_total` - a simple counter of the total number of times that recoveries enter exponential backoff,
- `walrus_recovery_future_backoffs` -  a single histogram recording the number of backoffs that each sliver recovery entered before collecting enough symbols,
- `walrus_recovery_future_failed_requests` - a single histogram recording the number of request failures that each sliver recovery encountered before collecting enough symbols, and
- `walrus_recovery_future_state` - a vector of gauges, one for each of 5 states, that gives insight to the state that each future is in when the metrics are being scraped.
Depends on #1976 
Observed metrics being exported in the local testbed.
---
Check each box that …

feat: add detailed metrics for recovering slivers

---

crates/walrus-service/src/node.rs
crates/walrus-simtest/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_failure.rs

We've seen cases where DB fail points may take longer to trigger.
---

test: simtest improvements: add event fail points to trigger node crash, and use checkpoint based event processor in all simtests

---

crates/walrus-e2e-tests/tests/test_client.rs
crates/walrus-sui/src/client.rs
crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs
crates/walrus-sui/src/test_utils.rs

Ensures that the coin selection process always returns 256 objects or less.
Since the coins are not returned in sorted order by balance, this change introduces a min-heap to keep track of the largest 256 coins encountered.
Closes WAL-429
---

fix(client): do not create transactions with more than 256 gas coins

---

crates/walrus-service/src/node.rs

The node ID metric added in #1857 was erroneously set to the capability object ID instead.
None.

fix(node): correctly set node_id metric

---

Cargo.lock
Cargo.toml
crates/walrus-service/src/node.rs

Contains a version bump to `v1.24.1` and important cherry-picks for the `v1.24` release:
- #2050

chore: v1.24.1 cherry-picks

---

crates/walrus-service/src/common/utils.rs

The same label `name` walrus widely uses is also used in monitored_scope.
Remove it for now, until we change it.
---

fix: remove mysten_metrics initialization

---

book.toml

This is necessary as the linkcheck keeps failing due to 429 responses from GitHub.

chore: ignore GH links during linkcheck

---

crates/walrus-service/src/node.rs

Before this change, some unit tests, specifically `recovers_sliver_from_only_symbols_of_one_type` were failing from time to time with an error `the blob has not been registered or has already expired`. This error occurs when attempting to store the metadata before the node received the registration event. With this change, storing the metadata is retried, thus avoiding the issue.
Test suite + stress testing the corresponding test with [cargo-stress](https://github.com/danhhz/cargo-stress):
```sh
cargo stress recovers_sliver_from_only_symbols_of_one_type
```

test: retry storing metadata during cluster creation

---

crates/walrus-service/src/node/committee/node_service.rs
crates/walrus-service/src/node/committee/request_futures.rs
crates/walrus-service/src/node/config.rs
crates/walrus-sui/benches/gas_cost_bench.rs

Limits the number of concurrent requests that are sent to each individual storage node. In the event that the limit has been reached for an individual storage node, the node is skipped when collecting nodes to send requests to. When coupled with the exponential backoff that is already implemented, requests that fail to find sufficient ready nodes will enter exponential backoff.
Existing tests. The performance impact has not been measured, but will need to be observed on PTN.
---
a user might notice and any actions they must take to implement updates. (Add …

refactor: limit concurrent requests sent to remote nodes

---

.licensesnipignore
Cargo.lock
Cargo.toml
crates/typed-store-derive/Cargo.toml
crates/typed-store-derive/src/lib.rs
crates/typed-store/Cargo.toml
crates/typed-store/src/lib.rs
crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks.rs
crates/typed-store/src/rocks/errors.rs
crates/typed-store/src/rocks/safe_iter.rs
crates/typed-store/src/rocks/tests.rs
crates/typed-store/src/traits.rs
crates/typed-store/tests/macro_tests.rs

Add typed store crate. The reasons for this change are as follows:
1. We can control Rocksdb version independent of Sui
2. The storage interface that Walrus needs is probably simpler than what typed-store provides and we also want to control this interface going forward (and likely simplify/change it according to our needs)
3. Using vanilla rust rocksdb is not enough since we lose out on metrics, perf context, etc. The plan is to first fork and then update rocksdb version.
---
a user might notice and any actions …

feat: Add typed store and derive crate to walrus repo

---

.pre-commit-config.yaml
crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_sync.rs
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/node/consistency_check.rs
crates/walrus-service/src/node/metrics.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-service/src/testbed.rs
crates/walrus-simtest/src/test_utils.rs

This PR implements the basic sliver data existence check conducted along with blob info consistency check
at beginning of every epoch. It exposes a metric which represents the percentage of fully synced blobs that
are actually fully stored. Note that here it has already taken blobs that are being synced into consideration.
Contribute to WAL-701
---

feat: blob sliver data existence check

---

crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node/config.rs

Storage nodes frequently cancel pending requests to other storage nodes when they are no longer relevant. This triggers a limit within the `h2` crate and an associated warning that pollutes the logs.
Until we change the behavior of cancelling pending requests, we can increase the limit to a very high value to effectively disable the check.
Contributes to WAL-660.
Set this value in our Mysten Labs 1 node on Mainnet.
---

fix(node): increase limit for number of pending accept reset streams

---

crates/walrus-service/src/node/dbtool.rs

Continues #1945
Closes #1944 
We had already made many of these changes in #1944. I noticed that two deprecated usages were reintroduced, so I opened this PR to fix them.
As a suggestion, we could consider adding `cargo check --features clap/deprecated` to a CI step to prevent future reintroductions of deprecated code. I can create PR to solve it.

fix: replace deprecated #[clap(...)] with #[command(...)] and #[arg(...)]

---

crates/walrus-service/src/common/utils.rs
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/committee/committee_service.rs
crates/walrus-service/src/node/config_synchronizer.rs

This PR reduces the verbosity level of a few types of log events:
- During each epoch change, there is a `ShardsReceived` event emitted for every node, so ~100 on our public networks. These don't need to be logged at the INFO level.
- Problems with pushing metrics don't affect the node operation itself and should thus be reduced from ERROR to WARN.
- Similarly, problems with config sync should only be WARN, not ERROR.
- The log entry `we are in the genesis epoch, not creating any services for committee members` is confusing, in particular as it is also emitted in epoch 1 when attempting to (re-)create services for committee members in the previous epoch. This is reformulated and reduced to DEBUG.
None.
---

fix(node): reduce level of some logging events

---

Cargo.toml

Ref : https://github.com/MystenLabs/walrus/pull/2076#pullrequestreview-2831985232
This PR adds a CI check step to prevent the reintroduction of deprecated `clap` attributes (`#[clap(...)]`).
```sh
cargo check --workspace --features clap/deprecated
```

chore: check for clap deprecations

---

.github/workflows/pages-preview.yaml
.github/workflows/publish-docs.yaml
setup/client_config.yaml

The wallet path was made optional in #2065, but this change is not yet included in the released version. This reverts the corresponding changes to the config file and also makes sure that the docs are updated when the config files change.
Look at docs preview and re-run the [compatibility test](https://github.com/MystenLabs/sui-operations/actions/workflows/walrus-scheduled-compatibility.yaml).

docs: keep wallet path in client config until `v1.26` is released

---

contracts/subsidies/Move.lock
contracts/subsidies/sources/subsidies.move
contracts/subsidies/tests/subsidies_tests.move
contracts/wal/Move.lock
contracts/wal_exchange/Move.lock
contracts/walrus/Move.lock
contracts/walrus/sources/system.move
crates/walrus-sui/src/contracts.rs

Add register_blob proxy call to subsidies contract. This would enable custom subsidies contract without modifying the client CLI significantly.
Also updated the subsidy calculation logic so that a buyer only needs to supply the post-subsidy portion of the WAL to pay for `extend_blob` and `reserve_space` calls. Before the update, a buyer has to supply the full amount of WAL of wall and then get refunded through the old `apply_subsidies` logic
Move test
---
a user might notice and any actions they must take to implement updates. (Add release notes after the …

chore: add register_blob call to subsidies contract

---

crates/walrus-simtest/tests/simtest_event_blob.rs
crates/walrus-sui/src/client/retry_client.rs
crates/walrus-sui/src/client/retry_client/failover.rs
crates/walrus-sui/src/client/retry_client/retriable_rpc_client.rs
crates/walrus-sui/src/client/retry_client/retriable_rpc_error.rs
crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs

- For both RPC client and Sui client, we only create it when using it. 
- Before this change, the primary RPC node must be available when node is starting up. This PR removes this setup and finds an available RPC node to use when need.
- For checkpoint not produced error, before we constantly switching to other clients. Instead, we should treat the error as retriable error and retry shortly.
simtest
---

fix: RPC node failure resistance improvement

---

Cargo.lock
crates/checkpoint-downloader/Cargo.toml
crates/checkpoint-downloader/src/config.rs
crates/checkpoint-downloader/src/downloader.rs
crates/walrus-service/node_config_example.yaml
crates/walrus-sui/src/client/retry_client/retriable_rpc_client.rs
crates/walrus-sui/src/client/retry_client/retriable_rpc_client/fallback_client.rs
crates/walrus-sui/src/client/rpc_config.rs

When an RetriableRpcClient encounters failures for extended period of time when fetching checkpoints from RPC nodes, the node should just skip RPC for short period of time, and directly fetch checkpoints from archival. Otherwise, the RPC request + retry + failure takes 40s to 60s, which significantly limits the checkpoint downloading throughput.
Tested archival catchup in PTN
---

fix: skip fetching checkpoint from rpc nodes when encounter extended primary failures

---

Cargo.lock
Cargo.toml
crates/checkpoint-downloader/src/downloader.rs
crates/typed-store/src/rocks/tests.rs
crates/walrus-orchestrator/src/settings.rs
crates/walrus-service/src/node/events/event_blob_writer.rs
crates/walrus-service/src/node/events/event_processor.rs

Too many warning when running simtest. We can roll forward once Sui 1.50 is released.
Related to WAL-834
Close WAL-790
---

chore: temporarily rollback tempfile dependency version.

---

crates/walrus-service/src/common/config.rs
crates/walrus-sui/src/client/retry_client/failover.rs
crates/walrus-sui/src/client/retry_client/retriable_rpc_client.rs
crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs

This was missed during the last round of GRPC proxy testing, and thanks @wbbradley for making the great
improvement to easily set RPC endpoints when creating SuiContractClient from a wallet!
Before this PR, if the endpoint specified in the wallet is unavailable, restarting the node won't work even other
RPC endpoints specified in the node config are still available. By only using the RPC endpoints from the config,
now SuiContractClient can correctly fall to the next client.
Changed back some simtest semantics from before #2052 since now the fall over should work.
---
For each box you select, include information after the relevant …

fix: use config PRC endpoints when creating SuiContractClient from wallet

---

crates/walrus-service/src/node/storage/database_config.rs

The metadata table is experiencing high volume of compaction, which may stall the writes for extended period of time.
---

feat: add options to update compaction write throttling, and set high write stalling threshold in metadata table

---

.github/workflows/code.yml
.github/workflows/scheduled_reports.yml
.github/workflows/updates.yml
Cargo.lock
Cargo.toml
contracts/subsidies/Move.lock
contracts/subsidies/Move.toml
contracts/wal/Move.lock
contracts/wal/Move.toml
contracts/wal_exchange/Move.lock
contracts/wal_exchange/Move.toml
contracts/walrus/Move.lock
contracts/walrus/Move.toml
crates/walrus-sui/src/config.rs
docker/walrus-antithesis/sui_version.toml

Bump all Sui dependencies to `testnet-v1.49.1`. Includes minor code adjustments in `crates/walrus-sui/src/config.rs` required due to https://github.com/MystenLabs/sui/pull/21983.

fix(deps): bump all Sui dependencies to `testnet-v1.49.1`

---

.github/workflows/trigger-artifacts-builds.yml

Since https://github.com/MystenLabs/sui-operations/actions/workflows/walrus-build-artifacts.yml expects to have `devnet`, `testnet`, and `mainnet` branches, so that it can build binaries for all platforms, the `releases/walrus-v1.25.0-release` branch does not make sense, since we re producing binaries `walrus-devnet-latest-windows-x86_64.tgz`
👀

ci: remove release branch builds trigger

---

docker/walrus-stress/Dockerfile

we need the walrus CLI binary for the `health` subcommand, so it's best to just bake the CLI binary into the stress image
ran docker build locally
---

chore: add walrus CLI binary to stress docker image

---

.vscode/settings.json

I often use multiple local repos, and by setting this in user setting doesn't work for me.
Since we are tracking the vscode setting now, adding the rust analyzer simtest option so that we don't need to always look for the option somewhere else.
---

chore: add simtest config option in vscode setting

---

contracts/subsidies/Move.lock
contracts/wal/Move.lock
contracts/wal_exchange/Move.lock
contracts/walrus/Move.lock
crates/walrus-sdk/src/client/client_types.rs
crates/walrus-sdk/src/error.rs
crates/walrus-service/src/client/multiplexer.rs
crates/walrus-service/src/node/committee/node_service.rs
crates/walrus-service/src/node/committee/test_committee_service.rs
crates/walrus-sui/src/client.rs
crates/walrus-sui/src/config.rs
crates/walrus-sui/src/test_utils.rs
docker/walrus-antithesis/build-walrus-image-for-antithesis/Dockerfile
docker/walrus-orchestrator/Dockerfile
docker/walrus-proxy/Dockerfile
docker/walrus-service/Dockerfile
docker/walrus-service/Dockerfile.walrus-backup
docker/walrus-stress/Dockerfile
rust-toolchain.toml

Clippy emitted a few new warnings [`result_large_err`](https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err) and [`large_enum_variant`](https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant) and suggested boxing some of the large variants/types.
This commit wraps some large (and rarely used) enum variants and error fields in a `Box` to avoid the memory overhead on the stack:
- `walrus_sdk::error::ClientError::kind`
- `walrus_service::node::committee::node_service::Response::InvalidBlobAttestation`
- `walrus_sui::client::SuiClientError::SuiError`
Two other instances of this lint warning are (temporarily) ignored. The commit also changes some instances of `.iter().any()` to the more efficient `contains()`.
Existing test suite.

refactor: bump Rust version to 1.87 and reduce size of some types

---

crates/walrus-sdk/Cargo.toml
crates/walrus-sdk/src/lib.rs
crates/walrus-sdk/src/utils.rs
crates/walrus-sui/Cargo.toml

Fix the dependency tree so that walrus_sdk crate should be usable by external tools without requiring importing transitive dependencies.
Local build of external tool.

chore: enable walrus-sdk to be linked by reference in external tools

---

contracts/walrus/sources/system.move
contracts/walrus/sources/system/system_state_inner.move
contracts/walrus/tests/system/storage_resource_tests.move
crates/walrus-sui/src/client.rs

Enables buying storage resources for future epochs, closes WAL-812
added test + existing tests
---

feat: enable buying storage resources for future epochs

---

.github/workflows/create-tx-for-multisig.yml
scripts/create_multisig_tx.sh

Adds a github action to create unsigned transactions for the walrus multisigs to upgrade/migrate the subsidies contract/object.
Contributes to WAL-675
- Manually ran script
- tested action locally with `act` (except for the uploading of the artifact)
---

chore: add github action to create transactions for multisig

---

crates/typed-store/src/rocks/errors.rs
crates/typed-store/src/rocks/safe_iter.rs
crates/typed-store/src/rocks/tests.rs
crates/typed-store/src/traits.rs

Will be used in node wide sliver existence check, so that we can do sequential scan instead of point lookup.
---

feat: allow SafeIter to seek to a specific key

---

crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node/storage/database_config.rs

Control WAL size and file count by
- max_total_wal_size
- keep_log_file_num
Also enable WAL archival.
Update metadata configuration by setting larger write buffer size and block cache size. The metadata table is the heaviest hit column family in nodes.
All these parameters have been verified in private testnet. Mainly the max_total_wal_size is able to control the active
log file size.
---

feat: RocksDB tuning

---

crates/walrus-e2e-tests/tests/test_client.rs
crates/walrus-sdk/src/config.rs
crates/walrus-service/bin/deploy.rs
crates/walrus-service/bin/node.rs
crates/walrus-service/src/client/cli/runner.rs
crates/walrus-service/src/client/multiplexer.rs
crates/walrus-service/src/common/config.rs
crates/walrus-service/src/common/utils.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-service/src/testbed.rs
crates/walrus-stress/src/generator/write_client.rs
crates/walrus-sui/src/system_setup.rs
crates/walrus-sui/src/test_utils.rs
crates/walrus-sui/src/test_utils/system_setup.rs
crates/walrus-sui/src/utils.rs
crates/walrus-sui/src/wallet.rs

Avoid deprecating `get_rpc_url` because in many cases it is the only rpc url we have and we do not have urgency around changing that.
CI Pipeline.

chore: remove deprecated status for get_rpc_url

---

crates/walrus-service/bin/deploy.rs
crates/walrus-service/src/client/cli/args.rs
crates/walrus-service/src/client/cli/runner.rs
crates/walrus-sui/src/client.rs
crates/walrus-sui/src/client/read_client.rs
crates/walrus-sui/src/client/transaction_builder.rs
crates/walrus-sui/src/system_setup.rs

- Adds a command to compute the package digest
- Separates the migrate command from the upgrade command
- Allows creating an unsigned transaction for the upgrade (to allow emergency upgrades from the multisig addr)
- Includes refactoring to build TransactionData in the WalrusPtbBuilder
- closes WAL-741
- Manual test of the new cli commands
---

feat: update commands for contract upgrades

---

crates/walrus-e2e-tests/tests/test_client.rs
crates/walrus-e2e-tests/tests/test_event_blobs.rs
crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/node/metrics.rs
crates/walrus-service/src/node/node_recovery.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-service/src/testbed.rs
crates/walrus-service/tests/epoch_change.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_failure.rs
crates/walrus-simtest/tests/simtest_param_sync.rs

For full node recovery, the memory usage grows when the number of live blobs in the system, which doesn't scale and may
cause OOM.
Simtest
Each modified simtest passed 100 seeds.
---

feat: rate limit concurrent blob recovery during node recovery

---

docs/book/SUMMARY.md
docs/book/walrus-sites/ci-cd.md

Create a page to share the github action with the rest of the community to automatically update their walrus sites.
This action is already running at the walrus landing page repo.

docs(walrus-sites): add a ci-cd section with an example gh action

---

Cargo.lock
scripts/release_notes.py

fix release generation when some commits don't have a body or a PR attached to it. This happens when there is a version bump that we force push to release branches sometimes.
Before:
```
python3 ./scripts/release_notes.py generate releases/walrus-v1.25.0-release releases/walrus-v1.26.0-release
Traceback (most recent call last):
File "/home/eugene/code/walrus/./scripts/release_notes.py", line 309, in <module>
do_generate(args["from"], args["to"])
File "/home/eugene/code/walrus/./scripts/release_notes.py", line 282, in do_generate
pr, notes = extract_notes_for_commit(commit)
File "/home/eugene/code/walrus/./scripts/release_notes.py", line 216, in extract_notes_for_commit
pr = json_data[0].get("number")
IndexError: list index out of range
```
After:
```
python3 ./scripts/release_notes.py …
```

ci: fix release generation

---

crates/walrus-sui/Cargo.toml
crates/walrus-sui/src/client/metrics.rs
crates/walrus-sui/src/client/retry_client.rs
crates/walrus-sui/src/client/retry_client/download_handler.rs
crates/walrus-sui/src/client/retry_client/retriable_rpc_client.rs
crates/walrus-sui/src/client/retry_client/retriable_rpc_client/fallback_client.rs
crates/walrus-sui/src/client/rpc_config.rs

The current implementation doesn't track single checkpoint failures for archival fallback as long as other checkpoints are successfully getting downloaded from the full node. This PR tries to fix that by adding sequence-specific failure tracking that persists until the problematic checkpoint succeeds:
- Only start tracking a new checkpoint's failures if we're not already tracking another one
- Reset failure metrics only for the specific checkpoint that succeeded
- Added `last_failed` to fallback eligibility check to provide more context
---
For each box you select, include information after the relevant heading that describes the …

feat: Make rpc client fallback on single checkpoint failures

---

crates/walrus-service/src/node/node_recovery.rs

A node restarting in recovery mode reads the `latest_event_epoch` before this is set properly (initially set to `0`).
This is a simple fix. A more robust solution for the future could be to store that in the DB and load it on start.
TBD.

fix(node): set latest_event_epoch correctly when restarting recovery

---

crates/walrus-service/src/node/node_recovery.rs

Cherry-picks #2179 into the `v1.26` release.
Tested through #2180. Deployment to Testnet.
---

chore(cherry-pick): set latest_event_epoch correctly when restarting recovery

---

crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_event_processor.rs
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/node/metrics.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-service/src/testbed.rs
crates/walrus-simtest/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_failure.rs

This PR improves storage node event processing speed by moving event action execution to a set of background workers.
Currently, processing certified events is somewhat slow due to blob data existence check, and sequentially processing
events makes event catchup slow. This is particularly problematic for storage nodes with lagging highest persisted
event. After restart, such node needs to reprocess events from the highest persisted event, and may take long time
to reach to the latest event.
By moving all but blob info update to background workers, the node can bring the blob info table to the latest state
faster, and therefore, reduce the window of highest processed event catchup.
This PR also adds a fallback config as if setting NodeBlobEventProcessorConfig::num_workers to 0, it fallback …

feat: non-blocking event processing

---

Cargo.lock
crates/walrus-service/src/common/event_blob_downloader.rs
crates/walrus-service/src/common/utils.rs
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/events/event_blob.rs
crates/walrus-service/src/node/events/event_blob_writer.rs
crates/walrus-simtest/Cargo.toml
crates/walrus-simtest/tests/simtest_event_blob.rs

This PR does:
1. Read latest certified event blob upon startup
2. Updates local state with latest certified if local state is behind
3. Delete previous local state
Added a new sim test to test
---

feat: Enable recovery from local node forking of event blobs

---

docs/book/walrus-sites/commands.md
docs/book/walrus-sites/routing.md
docs/book/walrus-sites/tutorial-publish.md

This commit updates the walrus-sites docs for the new 'deploy' command, 
which consolidates the functionality of 'publish' and 'update' into a streamlined workflow.
Key changes include:
- Added a section for the 'site-builder deploy' command in commands.md
- Added notes guiding users towards the new 'deploy' command.
- Updated the 'Publishing a Walrus Site' tutorial (tutorial-publish.md)
to use the 'deploy' command.
- Added a section about the `site_name` field of ws-resources.json
Edit: Note to self --> DO NOT MERGE BEFORE site-builder release

docs(walrus-sites): add 'deploy' command docs

---

crates/walrus-service/src/common/telemetry.rs

Switch to using a guard around the server active requests to ensure that the value always decrements.
---

fix: use a guard to ensure active request gauge decrements

---

crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/node/server.rs
crates/walrus-service/src/node/server/routes.rs

This adds the config parameter `rest_server.experimental_max_active_recovery_symbols_requests` which allows limiting the maximum number of active requests for symbols. A value of zero completely disables all recovery symbol endpoints (both individual and batch).
Depends on #2214 
Add a unit test which checks setting to zero.
---

feat: limit max recovery symbol requests

---

crates/walrus-service/src/node/metrics.rs

Adds an additional bucket to two recovery future metrics so that we can distinguish 1 failure or backoff from zero failures or backoffs.
---

fix: add zero bucket to recovery future metrics

---

crates/fan-out-proxy/src/client.rs
crates/fan-out-proxy/src/controller.rs
crates/fan-out-proxy/src/error.rs
crates/fan-out-proxy/src/params.rs
crates/fan-out-proxy/src/tip/config.rs

Ensures the `tx_id` and the `nonce` are not needed if the fan out is being run in "free" mode (`NoTip`).
Manual testing.
---

feat(fanout): do not require tx_id and nonce for free proxies

---

crates/walrus-service/src/node/config.rs

Reduce the default symbol request timeout to 45s down from 300s. Currently overloaded nodes do not load shed and as a result, response times increases for recovery symbols. Which slows down recoveries, this reduces the default timeout to a lower-yet-conservative value.
---

feat: reduce default recovery symbol request timeout

---

crates/walrus-service/bin/node.rs
crates/walrus-service/src/common.rs
crates/walrus-service/src/common/telemetry.rs
crates/walrus-service/src/common/utils.rs
crates/walrus-service/src/node.rs

This PR adds code for updating log directives to control logging verbosity dynamically at runtime through unix socket endpoint.
sudo /opt/walrus/bin/walrus-node local-admin --socket-path /opt/walrus/admin.socket log-level --level "info"
Log level updated successfully to: info
---

feat: Allow updating logging verbosity dynamically at runtime

---

crates/typed-store/src/rocks.rs
crates/typed-store/src/rocks/tests.rs
crates/typed-store/src/traits.rs
crates/walrus-service/src/event/event_processor/processor.rs
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_sync.rs
crates/walrus-service/src/node/event_blob_writer.rs
crates/walrus-service/src/node/storage/blob_info.rs
crates/walrus-service/src/node/storage/shard.rs
crates/walrus-simtest/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_event_blob.rs
crates/walrus-simtest/tests/simtest_failure.rs

Fount in antithesis test. ShardStorage currently is held as Arc<ShardStorage>, meaning that after epoch change that removes a shard and deletes all the column families in the shard, there may still be background process that may access the shard db. This can cause node crash.
To fix the issue, we make DBMap.cf() call return optional column family handle so that if a shard is removed, an error will be returned instead of crashing the node. DBMap.cf() is called in all DB operations.
Enhanced simtest to manifest this crash, and verified the fix.
---
a user …

fix: handling accessing shard db after shard removal

---

docker/walrus-orchestrator/Dockerfile
docker/walrus-proxy/Dockerfile
docker/walrus-service/Dockerfile
docker/walrus-service/Dockerfile.walrus-backup
docker/walrus-stress/Dockerfile

we're seeing rate limits from dockerhub, so let's use an internal repo to host the same image.
---

ci: replace base image to internal one to avoid rate limits

---

crates/walrus-service/src/node/blob_sync.rs

Found in antithesis, when a node is shutting down, internal sliver recover tasks may get cancelled. In #2228, we make
the cancellation error wrapped in `TypedStoreError::TaskError`. We should continue propagating the error back
instead of panicing in `panic!("database operations should not fail: {:?}", err)`.
---

chore: blob sync handles recover sliver cancellation

---

Cargo.lock
crates/walrus-service/Cargo.toml
crates/walrus-service/src/common/telemetry.rs
crates/walrus-service/src/node/server.rs

Report TLS expiration time in seconds since unix epoch.
Contributes to WAL-886.
Ran a local cluster and checked the expiration time exported.
---

feat: export the tls certificate expiration time as a metric

---

docker/walrus-antithesis/build-test-config-image/Dockerfile

this one should use public image as it's not built on our internal image building system
---

chore: antithesis image should use public image

---

crates/walrus-sdk/src/lib.rs
crates/walrus-sui/src/client.rs
crates/walrus-sui/src/client/read_client.rs
crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs
crates/walrus-sui/src/client/transaction_builder.rs
crates/walrus-sui/src/test_utils/system_setup.rs
crates/walrus-sui/src/utils.rs
crates/walrus-sui/tests/test_walrus_sui.rs

This PR modifies the CLI to proxy `register_blob` to subsidies contract as well as `reserve_space`. By doing so, this enables Walrus partners to pay zero WAL when interacting with the network. One the new subsidies contract is deployed. The code path should still work since this feature is dependent on subsidies_object being set in the config
New sim test
---

feat: use subsidies contract to proxy register blob call

---

crates/walrus-service/src/client/cli/runner.rs

This PR addresses an issue in the `ClientCommandRunner::blob_id` method, where a sui_read_client was being unnecessarily initialized, even when the `n_shards` argument was provided. This was leading to some rate-limit issues on the `walrus-sites/site-builder`, particularly when trying to deploy a site with a large number of files. 
Related [linear issue](https://linear.app/mysten-labs/issue/SEW-288/error-error-while-computing-the-blob-id-for-path) & [walrus-sites PR](https://github.com/MystenLabs/walrus-sites/pull/512). 
Initially I fixed the issue on the site-builder repo by supplying the `encoding_type` as well, when running the `blob_id` method, however, after discussing with my team, we feel it makes more sense to address this here, especially since it is a tiny change. 
On a side …

fix(cli): Avoid unnecessary sui_read_client initialization in blob_id command

---

setup/client_config.yaml

Since the `v1.26` release, the wallet path in the Walrus config is optional.

docs: make wallet path optional in config file

---

crates/checkpoint-downloader/src/config.rs
crates/checkpoint-downloader/src/downloader.rs
crates/checkpoint-downloader/src/metrics.rs

When the channel is full, sending may be blocked, and at the same time, we cannot consume any checkpoints, so the loop
may be stuck forever.
---

chore: sending checkpoint to download checking if the channel is full

---

.github/workflows/update-ws-install.yaml
docs/book/usage/setup.md

- Add missing Linux aarch64 target.
- Add installation with `suiup`.
- Use `install.wal.app` for the installation script.
- Add a CI job to keep the `install.wal.app` site up to date.
Inspect docs preview and check workflow run after merge.

docs: improve installation instructions

---

crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_event_processor.rs
crates/walrus-service/src/node/blob_sync.rs
crates/walrus-service/src/node/node_recovery.rs
crates/walrus-simtest/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_failure.rs

Previously, storage node assumed that a node recovery should finish within 1 epoch length, and if during node
restart, the node sees it is in RecoveryInProgress(epoch) state, and the epoch is lagging behind, it assumed that
the node is lagging again, and then directly enter RecoveryCatchUp mode.
However in practice, we have seen that it is not uncommon that the RecoveryInProgress takes more than 1 epoch.
Restarting node after epoch change would make the node goes back to RecoveryCatchup mode and therefore
not recovering any blobs until next epoch change, which can be 1 epoch length away (2 weeks on mainnet)
This PR addresses this issue by allowing in progress node recovery to continue after node restart. A list of changes
are made to achieve this goal:
- During epoch change, ongoing node …

feat: continue node recovery upon restart if the recovery takes longer than 1 epoch to finish

---

crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_event_processor.rs
crates/walrus-service/src/node/blob_sync.rs
crates/walrus-service/src/node/node_recovery.rs
crates/walrus-simtest/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_failure.rs

* Continue node recovery upon restart if the recovery takes longer than 1 epoch to finish
* use a watch channel to set latest_event_epoch
* fix simtest_test_long_node_recovery
* allow current_event_epoch to be optional, and skip events before the first epoch change when recovering from an incomplete history
* start_node_recovery hooks to previous blob sync notify handle
* seperate current_event_epoch implementation to wait for it to be populated
* Add test
* cleanup
* address comments
* stop node recovery if the node enters RecoverCatchUp
---
For each box you select, include …

feat: [cherry-pick] continue node recovery upon restart if the recovery takes longer than 1 epoch to finish (#2291)

---

.github/workflows/code.yml

We use the `testnet-contracts` as basis for the upgrade tests in Rust, so we should run the Rust tests if those change as well. This caused the issue in the CI yesterday, because I forgot to bump the VERSION in the `contracts/walrus/[system|staking].move` files.
---

fix: run rust tests in CI if testnet-contracts change

---

.github/workflows/publish-docs.yaml
.github/workflows/update-ws-binaries.yaml
.github/workflows/update-ws-install.yaml

Otherwise, we could end up with conflicting transactions and locked objects.

ci: ensure WFs involving Sui transactions are not concurrent

---

crates/walrus-service/src/event/event_processor/checkpoint.rs
crates/walrus-service/src/event/event_processor/processor.rs

Cherry-picks #2318.
Deploy to Testnet node.

fix: use original package ID to filter events (cherry-pick)

---

crates/walrus-service/src/backup/garbage_collector.rs

Ensure that backup blobs live longer than their expiry by 2 extra epochs to make them more available for emergency use-cases.
CI Pipeline

chore: extend the backup lifetime of archived blobs

---

crates/walrus-sdk/src/client/refresh.rs

Reduces the log level for three log statements in the SDK:
- `the channel is closed, stopping the refresher` is not useful for most people and may cause confusion.
- `failed to refresh the active committee; retrying again at the next interval` is not critical and should thus just be a warning (no error).
Not needed.

fix(sdk): reduce verbosity of some log entries

---

crates/walrus-service/src/event/event_blob_downloader.rs
crates/walrus-simtest/tests/simtest_param_sync.rs

It's possible that 1 certified status from 1 storage node results in `read_blob_status()` returning certified status, but
event blob may still not be available for reads due to delay in propagating register/certify events to other storage nodes.
Similar to reading the blob status, also retrying reading first event blob if encountering non-existence error.
100 test_registered_node_update_protocol_key run passed, was failing with high probability before.
---
a user might notice and any actions they must take to implement updates. (Add release notes after the …

fix: retry reading first event blob when encounter non-exist error

---

.github/workflows/code.yml
.github/workflows/scheduled_reports.yml
.github/workflows/updates.yml
Cargo.lock
Cargo.toml
contracts/subsidies/Move.lock
contracts/subsidies/Move.toml
contracts/wal/Move.lock
contracts/wal/Move.toml
contracts/wal_exchange/Move.lock
contracts/wal_exchange/Move.toml
contracts/walrus/Move.lock
contracts/walrus/Move.toml
contracts/walrus_subsidies/Move.lock
contracts/walrus_subsidies/Move.toml
crates/walrus-service/src/node/blob_sync.rs
crates/walrus-sui/src/client/retry_client.rs
deny.toml
docker/walrus-antithesis/sui_version.toml

Bumps all Sui dependencies to the [latest Testnet release](https://github.com/MystenLabs/sui/releases/tag/testnet-v1.52.1). This required very minor code changes and changes to the `deny.toml` file.

fix(deps): bump all Sui dependencies to `testnet-v1.52.1`

---

crates/walrus-e2e-tests/tests/test_client.rs
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/contract_service.rs
crates/walrus-service/src/node/epoch_change_driver.rs
crates/walrus-service/src/node/start_epoch_change_finisher.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-service/src/testbed.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-sui/src/client.rs
crates/walrus-sui/src/client/contract_config.rs
crates/walrus-sui/src/client/read_client.rs
crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs
crates/walrus-sui/src/client/transaction_builder.rs
crates/walrus-sui/src/contracts.rs
crates/walrus-sui/src/system_setup.rs
crates/walrus-sui/src/test_utils/system_setup.rs
crates/walrus-sui/src/types/move_structs.rs

Schedules a call to process the subsidies on storage nodes, to be called shortly before epoch change.
Added test in e2e-tests.
---

feat: schedule call to process subsidies

---

crates/walrus-sdk/src/error.rs
crates/walrus-service/src/event/event_blob_downloader.rs

This is another ClientError that can be returned when the latest certified event blob is being propagated to storage
nodes.
100 simtest_test_registered_node_update_protocol_key
---

fix: count ClientErrorKind::NoMetadataReceived as blob not exist when reading event blob

---

.github/workflows/attach-binaries-to-release.yml

Fix for #2367.
See [this workflow run](https://github.com/MystenLabs/walrus/actions/runs/16477073816/job/46581467339).

ci: fix GCP bucket name for upload

---

crates/walrus-service/Cargo.toml
crates/walrus-service/bin/node.rs
crates/walrus-service/src/node/committee/node_service.rs
crates/walrus-service/src/node/config_synchronizer.rs
crates/walrus-service/src/node/server.rs

- Only restart the node if the currently loaded certificate is about to expire or the subject or extensions have changed.
- Log warnings when the certificate on disk is about to expire.
- Log errors when the certificate is expired.
- Don't log an error when a node restart is caused by a changed configuration.
As certificates are normally valid for 3 months and renewed every month, while nodes are restarted ever 2 weeks due to new releases, this approach virtually guarantees that the node never restarts automatically because of an updated certificate.
Closes WAL-832
Closes WAL-886
Modified/added unit test.
---

fix(node): handle updated TLS certificates more gracefully

---

mainnet-contracts/subsidies/Move.toml
mainnet-contracts/wal/Move.toml
mainnet-contracts/walrus/Move.lock
mainnet-contracts/walrus/Move.toml
mainnet-contracts/walrus/docs/msg_formats.txt
mainnet-contracts/walrus/sources/display.move
mainnet-contracts/walrus/sources/init.move
mainnet-contracts/walrus/sources/staking.move
mainnet-contracts/walrus/sources/staking/active_set.move
mainnet-contracts/walrus/sources/staking/apportionment_queue.move
mainnet-contracts/walrus/sources/staking/committee.move
mainnet-contracts/walrus/sources/staking/staking_inner.move
mainnet-contracts/walrus/sources/staking/staking_pool.move
mainnet-contracts/walrus/sources/staking/storage_node.move
mainnet-contracts/walrus/sources/system.move
mainnet-contracts/walrus/sources/system/bls_aggregate.move
mainnet-contracts/walrus/sources/system/event_blob.move
mainnet-contracts/walrus/sources/system/events.move
mainnet-contracts/walrus/sources/system/messages.move
mainnet-contracts/walrus/sources/system/shared_blob.move
mainnet-contracts/walrus/sources/system/storage_accounting.move
mainnet-contracts/walrus/sources/system/storage_resource.move
mainnet-contracts/walrus/sources/system/system_state_inner.move
mainnet-contracts/walrus/tests/e2e_runner.move
mainnet-contracts/walrus/tests/e2e_tests.move
mainnet-contracts/walrus/tests/system/blob_tests.move
mainnet-contracts/walrus/tests/system/deny_list_tests.move
mainnet-contracts/walrus/tests/system/storage_resource_tests.move
mainnet-contracts/walrus/tests/test_node.move
mainnet-contracts/walrus/tests/test_utils.move

This PR prepares the walrus mainnet contracts for the planned upgrade. The branch is used for voting on the upgrade and should only be merged once the upgrade is committed.
Edit: The upgrade is now committed on chain, the new package address is `0xfa65cb2d62f4d39e60346fb7d501c12538ca2bbc646eaa37ece2aec5f897814e`
---

chore: prepare mainnet contracts for upgrade

---

contracts/subsidies/Move.lock
contracts/wal/Move.lock
contracts/wal_exchange/Move.lock
contracts/walrus/Move.lock
contracts/walrus_subsidies/Move.lock
contracts/walrus_subsidies/sources/walrus_subsidies.move
testnet-contracts/walrus_subsidies/sources/walrus_subsidies.move

I discovered that after deploying the walrus_subsidies contract on testnet, I accidentally bumped the version on the `testnet-contracts` instead of `contracts`. This fixes that. I checked that the correct version is deployed on testnet.
---

fix: use correct version in testnet-contracts

---

Cargo.lock
crates/walrus-e2e-tests/tests/test_client.rs
crates/walrus-service/src/event/event_processor/processor.rs
crates/walrus-simtest/Cargo.toml
crates/walrus-simtest/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_event_blob.rs
crates/walrus-sui/src/client.rs
crates/walrus-sui/src/system_setup.rs

This PR moves the test `test_quorum_contract_upgrade` to simtest environment, but I had to do a few changes to make it work. This is the main difference from tokio env about waiting for nodes to reach a particular epoch:
```
// Wait for the nodes to reach the migration epoch.
let target_epoch = upgrade_epoch + 1;
loop {
let mut all_nodes_ready = true;
for node in &walrus_cluster.nodes {
let current_epoch = simtest_utils::get_current_epoch_from_node(node).await;
if current_epoch < target_epoch {
all_nodes_ready = false;
break;
}
}
if all_nodes_ready {
break;
}
tokio::time::sleep(Duration::from_secs(5)).await;
}
```
And then I also added restart of all nodes after package upgrade as that is what actually changes their view of the current package id in event processor. To ensure things work …

feat: Move test_quorum_contract_upgrade test to simtest env

---

crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node/storage/database_config.rs

(This is the second attempt to cleanup the database column family option hierarchy)
The existing DatabaseConfig is quite confusing. First of all, DatabaseTableOptions defines all the default CF options (standard, optmized_for_blobs), and then the DatabaseConfig can override any of these basic template, as well as any
individual CF options. What's more confusing is that when overriding the basic template, we take, e.g. DatabaseConfig::standard, only from DatabaseConfig completely, but when overriding individual CF options, it inherits the basic option first, and then override any fields that exist in the DatabaseConfig.
This PR attempts to make DB option setup clearer and not introduce any breaking change.  
First of all, DatabaseTableOptions now defines 4 template options: standard, …

chore: cleanup database table options hierarchy

---

.github/workflows/create-tx-for-multisig.yml
scripts/create_multisig_tx.sh

Adds a command to set the subsidy rates in the new `walrus_subsidies` object.
Also cleans up commands for the old subsidies that are no longer used after the multisig from [this workflow run](https://github.com/MystenLabs/walrus/actions/runs/16620981332) goes through.
Locally ran script with dry-run (instead of serialized-unsigned) to check that the transaction gets created correctly.
---

chore: add multisig for setting subsidy rates to workflow

---

contracts/README.md
crates/walrus-sdk/src/config.rs
crates/walrus-sui/src/client.rs
crates/walrus-sui/src/client/contract_config.rs
crates/walrus-sui/src/client/read_client.rs
crates/walrus-sui/src/client/transaction_builder.rs
crates/walrus-sui/src/contracts.rs
crates/walrus-sui/src/test_utils/system_setup.rs
crates/walrus-sui/src/types/move_structs.rs
docs/book/dev-guide/costs.md
docs/book/usage/networks.md
docs/book/usage/setup.md
scripts/local-testbed.sh
setup/client_config.yaml
setup/client_config_mainnet.yaml

Closes WAL-905
Closes WAL-908
Existing tests, added test to ensure that old configs don't break the client.
---

chore: clean up old subsidies in the client and docs

---

crates/walrus-service/src/node/blob_event_processor.rs
crates/walrus-service/src/node/consistency_check.rs
crates/walrus-service/src/node/event_blob_writer.rs
crates/walrus-service/src/node/storage.rs
crates/walrus-service/src/node/storage/blob_info.rs
crates/walrus-simtest/tests/simtest.rs

Previously, the node would not handle blob deletions and invalidations correctly while catching up with incomplete history. This makes the following changes:
- Allow handling `InvalidBlobId` events even when the corresponding blob is not yet tracked.
- Allow setting the `is_metadata_stored` flag for blobs that are not yet tracked.
- Do not log warnings when handling `BlobDeleted` events for untracked blobs while catching up with incomplete history.
Closes WAL-947
Also contributes to WAL-553 (fix skipping event blobs when starting with an incomplete history).
Started a new node on Testnet and had it catch up. No errors or warnings in the logs.
TODO:

fix(node): fix handling of invalid blobs and deletions with incomplete history

---

.github/workflows/create-release-announce.yml

It is crucial that the Sui version used for dependencies is as close to the deployed Sui version as possible. Lagging more than one minor version behind has caused outages in the past.
With this added check, we make sure to have an up-to-date Sui version in our dependencies when creating a new devnet release.
The check can be disabled to allow for special cases, for example, when using a specific commit for the dependencies instead of a tag.
Ran the added script manually with the expected results.

ci: check if latest Sui version is used before creating a devnet release

---

.github/workflows/create-release-announce.yml
scripts/release_notes.py

verify notes field:
```
Traceback (most recent call last):
File "/home/runner/work/walrus/walrus/./scripts/release_notes.py", line 309, in <module>
do_generate(args["from"], args["to"])
File "/home/runner/work/walrus/walrus/./scripts/release_notes.py", line 282, in do_generate
pr, notes = extract_notes_for_commit(commit)
File "/home/runner/work/walrus/walrus/./scripts/release_notes.py", line 217, in extract_notes_for_commit
return parse_notes(pr, message)
File "/home/runner/work/walrus/walrus/./scripts/release_notes.py", line 112, in parse_notes
match = RE_HEADING.search(notes)
TypeError: expected string or bytes-like object
```
```
eugene@eugene-dev ~/code/walrus (ebmifa/fix_release_create) $ python3 ./scripts/release_notes.py generate b37047ff2adbfab3fe38da69bf8609b29c884e33 …
```

fix: verify notes field

---

docs/book/walrus-sites/routing.md

The documentation incorrectly refers to `ws-resource.json`,  
but the correct filename is `ws-resources.json`.  
This PR fixes the typo.

chore: fix typo in ws-resources.json filename

---

crates/walrus-sui/src/client/retry_client/retriable_rpc_error.rs

The RPC can sometimes timeout if it is under load or during epoch change. It is important to retry within the retry client to ensure that the same transaction is repeated (and therefore no locked objects can occur).
---

fix(client): add HTML error codes to retriable RPC errors

---

crates/walrus-core/src/encoding.rs
crates/walrus-core/src/encoding/common.rs
crates/walrus-core/src/encoding/config.rs
crates/walrus-core/src/encoding/errors.rs
crates/walrus-core/src/encoding/slivers.rs
crates/walrus-core/src/encoding/symbols.rs
crates/walrus-core/src/inconsistency.rs
crates/walrus-core/src/lib.rs
crates/walrus-core/src/merkle.rs
crates/walrus-core/src/test_utils.rs
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/committee/node_service.rs
crates/walrus-service/src/node/committee/request_futures.rs
crates/walrus-service/src/node/committee/test_committee_service.rs
crates/walrus-service/src/node/storage.rs
crates/walrus-storage-node-client/src/client.rs
crates/walrus-sui/benches/gas_cost_bench.rs

This PR ensures that we only perform cryptographic validation of inconsistency proofs and recovery symbols after performing some checks on the size of them and their proofs.
Also adds some clarifying comments and docstrings and cleans up no-longer-used functions.
Existing/adapted tests.

fix: add simple checks to avoid unnecessary computations where possible

---

.github/workflows/stale-prs.yaml

The workflow runs once per week, marking PRs that weren't touched in more than 2 weeks as stale and closing them one week afterwards.
Run workflow manually after merging this PR.

ci: add workflow that marks and closes stale PRs

---

crates/walrus-core/src/encoding/blob_encoding.rs
crates/walrus-core/src/encoding/config.rs
crates/walrus-sdk/src/client.rs
crates/walrus-sdk/src/client/client_types.rs
crates/walrus-service/src/event/event_processor/checkpoint.rs
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_retirement_notifier.rs
crates/walrus-service/src/node/epoch_change_driver.rs
crates/walrus-service/src/node/server/openapi.rs
crates/walrus-service/src/node/storage.rs
crates/walrus-service/src/node/storage/blob_info.rs
crates/walrus-sui/src/client/read_client.rs
crates/walrus-sui/src/types/move_structs.rs
crates/walrus-utils/src/metrics/monitored_scope.rs
rust-toolchain.toml

Bumps Rust to the latest stable toolchain and fixes all new lint warnings (some with `cargo clippy --fix`, some manually). 
CI.

chore: bump Rust to 1.89 and fix new lint warnings

---

Cargo.lock
Cargo.toml
contracts/subsidies/Move.lock
contracts/subsidies/Move.toml
contracts/wal/Move.lock
contracts/wal/Move.toml
contracts/wal_exchange/Move.lock
contracts/wal_exchange/Move.toml
contracts/walrus/Move.lock
contracts/walrus/Move.toml
contracts/walrus_subsidies/Move.lock
contracts/walrus_subsidies/Move.toml
crates/walrus-service/daemon_openapi.yaml
crates/walrus-service/publisher_openapi.yaml
crates/walrus-service/storage_openapi.yaml
crates/walrus-upload-relay/upload_relay_openapi.yaml
docker/walrus-antithesis/sui_version.toml
testnet-contracts/subsidies/Move.lock
testnet-contracts/subsidies/Move.toml
testnet-contracts/wal/Move.lock
testnet-contracts/wal/Move.toml
testnet-contracts/wal_exchange/Move.lock
testnet-contracts/wal_exchange/Move.toml
testnet-contracts/walrus/Move.lock
testnet-contracts/walrus/Move.toml
testnet-contracts/walrus_subsidies/Move.lock
testnet-contracts/walrus_subsidies/Move.toml

* chore: bump sui dep version to testnet-v1.54.0
Keep Walrus sui deps in sync.

chore: bump sui dep version to testnet-v1.54.0 (#2432)

---

crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks.rs
crates/typed-store/src/rocks/safe_iter.rs

This PR introduces some granular metrics for typed-store to provide better visibility into database operations, especially for point lookups:
1. Negative Lookup Metric to allows distinguishing between lookups for existing keys and non-existing keys (negative lookups). Added to `contains_key` and `get`
2. Metrics to track both `key` and `value` bytes separately which offers deeper insight into data usage pattern.
3. The logic for managing iterator-related metrics is refactored into a new IterContext struct.
Existing tests

feat: Add metric to track negative point lookups and granular data usage

---

docs/book/operator-guide/upload-relay.md
docs/book/usage/client-cli.md
docs/book/usage/web-api.md

Explicitly describe how the blob persistence can be controlled in the CLI and publisher API and warn about the default change in 1.33.
Contributes to WAL-911.
Inspect the preview.

docs: explicitly warn about change of default blob persistence

---

crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks.rs

We currently only expose RocksDB-wide bloom metrics via tickers. To debug skewed bloom behavior and table-level hot spots, we need per–column family visibility into bloom positives and false positives. Added two per-CF Prometheus counters in typed-store:
`rocksdb_bloom_filter_may_exist_true_total{cf_name}`: counts when key_may_exist_cf returns true.
`rocksdb_bloom_filter_false_positive_total{cf_name}`: counts when key_may_exist_cf is true but subsequent get returns None.

feat: Add metrics to compute false positive rate per column family in RocksDB

---

crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_sync.rs

Previously in #2326 , we found that when the first event after a node restart is an epoch change event, we need to
set the latest event epoch to the previous epoch, since the epoch change hasn't been executed yet. What can happen
now is that after setting the epoch to the previous epoch, the `latest event epoch` may be 2 epochs earlier than the
latest epoch on chain. This can cause blob sync initiated by node recovery task to fail since we try to recover
blobs that are from 2 epochs ago.
The fix for this issue is that instead of setting the epoch to the previous epoch, we don't set `latest event epoch`
when the first event is an epoch change event. This is because after the epoch change event is executed, it will
set it to the latest one. In this case, blob recovery will always uses the …

fix: skip setting latest event epoch when the first event is an epoch change event after node restart

---

crates/walrus-service/src/client/cli/args.rs

The missing `serde(default)` meant that the `paths` argument always had to be included when using the JSON mode.
Manual test.

fix(client): fix JSON parsing of storeQuilt options

---

crates/typed-store/src/metrics.rs
crates/typed-store/src/rocks.rs
crates/walrus-service/src/node/storage/database_config.rs

This PR allows us to enable RocksDB statistics at runtime through database config change. Also adds some db compaction related statistics  to be tracked.

feat: Enable Rocksdb statistics at runtime through config

---

.config/nextest.toml
crates/walrus-upload-relay/src/controller.rs

Make sure we catch inconsistent example files in CI by turning off retries for the corresponding tests.
Also reduce the default number of retries to 1 to catch excessively flaky tests.
Run the CI with an inconsistency introduced by a test commit 62f4b04b7568aabaa3d8f6aab276be901097b840: https://github.com/MystenLabs/walrus/actions/runs/17297627090/job/49099781547?pr=2478

ci: make sure we catch inconsistent example files

---

docs/book/SUMMARY.md
docs/book/walrus-sites/avoid-duplicate-content-seo.md

This pull request adds new documentation to help users avoid duplicate-content SEO issues when deploying custom Walrus Sites portals. The main focus is on providing guidance for canonicalization and best practices to ensure search engines do not penalize sites for duplicate content.
Documentation updates:
* Added a new section to the table of contents in `SUMMARY.md` for avoiding duplicate-content SEO in custom portals.
* Created a new page, `avoid-duplicate-content-seo.md`, with detailed recommendations on canonical host policies, handling of base36 and BYOD domains, implementation examples for redirects and headers, and advice for managing multiple SuiNS names for a single site.

docs: add section on avoiding duplicate-content SEO in custom portals

---

crates/walrus-core/src/encoding/basic_encoding.rs
crates/walrus-sdk/src/client.rs
crates/walrus-sdk/src/client/refresh.rs
crates/walrus-sdk/src/client/resource.rs
crates/walrus-sdk/src/config/committees_refresh_config.rs
crates/walrus-service/src/client/cli/runner.rs
crates/walrus-service/src/client/daemon.rs
crates/walrus-service/src/client/refill.rs
crates/walrus-sui/src/client.rs
crates/walrus-sui/src/client/read_client.rs
crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs

When sending a request to the publisher to store a blob that was already stored, certification would be skipped but a transaction would be sent to Sui regardless due to not checking if there were no blobs to put into the PTB. This fixes that skips several code paths when the list on which they would be operating is empty.
Additionally, this tidies some of the tracing export to reduce noise in trace exports.
---

fix: do not send trasnaction if blob already certified, tidy publisher traces

---

crates/walrus-service/src/backup/config.rs
crates/walrus-service/src/backup/garbage_collector.rs
crates/walrus-service/src/backup/service.rs

Fix a regression in garbage collection statistics in walrus-backup. The regression was introduced recently in 7321bdf9431841f75afc97e6927be35c548cbbb3 wherein I delayed the garbage collection mechanism until 2 epochs later than expiry, but failed to update the related stats collection.
CI Pipeline.

fix: fix walrus-backup garbage collection statistics

---

crates/walrus-e2e-tests/tests/test_client.rs
crates/walrus-service/src/node/event_blob_writer.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs
crates/walrus-simtest/tests/simtest_param_sync.rs

There were some instances where ports were not being released in time for retries. This change unifies the unused_socket_address code paths and leverages them in the upload relay tests.
CI Pipeline.

chore: reduce test failures of upload relay due to port conflicts

---

.github/actions/build-mdbook/action.yaml
README.md
book.toml
docs/book/assets/portals.json
docs/book/portals/list.json
docs/book/usage/web-api.md
docs/book/walrus-sites/portal.md

This pull request updates the documentation to introduce and display a list of known portals for the project. It adds a new JSON data file for portals, updates the configuration to include this data, and enhances the documentation to show the list and explain how new portals can be added.
**Documentation updates for portals:**
* Added a new file, `docs/book/portals/list.json`, which contains the list of known portals and their operators.
* Updated `book.toml` to include `docs/book/portals/list.json` as a data source for the templates preprocessor, allowing portal data to be used in documentation.
* Enhanced `docs/book/walrus-sites/portal.md` to explain how new portals can be added and to display the list of known portals using a template block.

chore: [docs] update portal configuration and add new portals list

---

Cargo.lock
Cargo.toml
contracts/subsidies/Move.lock
contracts/subsidies/Move.toml
contracts/wal/Move.lock
contracts/wal/Move.toml
contracts/wal_exchange/Move.lock
contracts/wal_exchange/Move.toml
contracts/walrus/Move.lock
contracts/walrus/Move.toml
contracts/walrus_subsidies/Move.lock
contracts/walrus_subsidies/Move.toml
docker/walrus-antithesis/sui_version.toml
scripts/bump_sui_testnet_version.sh
testnet-contracts/subsidies/Move.lock
testnet-contracts/subsidies/Move.toml
testnet-contracts/wal/Move.lock
testnet-contracts/wal/Move.toml
testnet-contracts/wal_exchange/Move.lock
testnet-contracts/wal_exchange/Move.toml
testnet-contracts/walrus/Move.lock
testnet-contracts/walrus/Move.toml
testnet-contracts/walrus_subsidies/Move.lock
testnet-contracts/walrus_subsidies/Move.toml

This PR updates the Sui testnet version to testnet-v1.57.0

ci: bump Sui testnet version to testnet-v1.57.0 in `releases/walrus-v1.33.0-release` branch

---

crates/typed-store/src/rocks.rs
crates/walrus-core/src/lib.rs
crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/node/storage/shard.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-simtest/tests/simtest.rs

This PR introduces an optional, high-throughput write path for shard sync that ingests sliver data via RocksDB SST files instead of per-key batched writes. It also adds typed-store utilities to build and ingest SSTs safely. The feature is disabled by default and can be toggled per node via config.
The primary motivation for doing this work is during shard sync, the node downloading the shard does writes to shard column family at a high rate which causes compaction to back up and slow down (or potentially stall) *writes to the entire db* which is not great. Writing data through sst files is also the recommended way of bulk ingesting data according to RocksDB wiki.
Added unit tests, and the rollout will be done initially only on testnet.

feat: Make shard sync directly ingest data in sst files

---

crates/walrus-service/src/node.rs
crates/walrus-service/src/node/blob_event_processor.rs
crates/walrus-service/src/node/blob_sync.rs
crates/walrus-simtest/tests/simtest_failure.rs

test_repeated_node_crash exposes a bug where the first blob certified event may not trigger blob sync due to that
the blob may have been expired based on the current committee epoch. However, in the same epoch where
the blob was expired based the first certified event, the blob may be extended. Currently, blob extension does not
trigger blob sync, which may leave the node to miss the data.
To fix this issue, we need to allow blob extension event to also trigger blob sync if the blob misses some shard data.
There is another complication associated with this method because `current_event_epoch()` may not be available
to use to check blob data integrity. In this case, we just need to blindly start the blob sync: if the blob is fully stored,
blob sync still won't do any work.
200 …

fix: extending blob at the latest epoch

---

CONTRIBUTING.md
Cargo.toml
crates/walrus-core/src/encoding/basic_encoding.rs
crates/walrus-core/src/encoding/blob_encoding.rs
crates/walrus-core/src/encoding/config.rs
crates/walrus-core/src/encoding/slivers.rs

In the past, when we were using RaptorQ for the 1D encoding, it was necessary to keep around intermediate decoding state as the exact number of slivers needed for decoding was unknown and we would potentially have to reuse the decoder for a new decoding attempt.
This is no longer the case with Reed-Solomon, as we know the exact number of slivers needed for decoding. As a result, we can allocate a single 1D decoder and reuse it for all sub-decodings during blob decoding.
This commit also makes some other changes to reduce the number of allocations during blob decoding, specifically by using flat arrays instead of nested vectors where possible.
Both together result in both a **major reduction in memory usage** and a **significant performance improvement**:
- The peak memory usage while …

fix(core): optimize memory allocations during blob decoding

---

crates/walrus-e2e-tests/tests/test_client.rs
crates/walrus-sdk/src/client.rs
crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/node.rs
crates/walrus-service/src/node/config.rs
crates/walrus-service/src/node/storage.rs
crates/walrus-service/src/node/storage/blob_info.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-service/src/testbed.rs
crates/walrus-sui/src/test_utils.rs

For deletable blobs, we store object counts in the aggregate blob info. These need to be updated when deletable blobs expire.
This adds a new (background) task running at the beginning of each epoch that cleans up expired entries in the per-object blob info and updates the aggregate blob info for expired deletable blobs.
This also improves some test utils and fixes several E2E tests that reused object IDs in an incorrect way.
A newly added E2E test (`test_storage_nodes_do_not_serve_data_for_expired_deletable_blobs`) verifies that this works correctly. I verified that the test fails without the added `process_expired_blob_objects` task and succeeds with it.

feat(node): update blob info when deletable blobs expire

---

crates/walrus-core/src/encoding/blob_encoding.rs
crates/walrus-core/src/encoding/config.rs
crates/walrus-core/src/encoding/mapping.rs
crates/walrus-core/src/encoding/quilt_encoding.rs
crates/walrus-core/src/encoding/slivers.rs
crates/walrus-core/src/inconsistency.rs
crates/walrus-sdk/src/client/quilt_client.rs

Remove unnecessary references around EncodingConfigEnum causing unnecessary bloat in impls of EncodingFactory
No functional changes. CI Pipeline.

chore: remove unnecessary reference in EncodingConfigEnum

---

crates/walrus-service/src/node.rs
crates/walrus-service/src/node/metrics.rs

Exports the Sui checkpoint from which the last processed walrus event was taken. This allows us to
- determine storage node lag independently of other storage nodes, and without a global view of the network (currently we measure this by how far behind a storage node is relative to other nodes; and
- determine the delay between a Sui checkpoint and a node actually processing the related walrus events, which is an input to write latency.
---
a user might notice and any actions they must take to implement updates. …

feat: export the Sui checkpoint of the last processed Walrus event

---

crates/checkpoint-downloader/src/downloader.rs
crates/walrus-service/node_config_example.yaml
crates/walrus-service/src/event/event_processor.rs
crates/walrus-service/src/event/event_processor/catchup.rs
crates/walrus-service/src/event/event_processor/config.rs
crates/walrus-service/src/event/event_processor/coordination.rs
crates/walrus-service/src/event/event_processor/metrics.rs
crates/walrus-service/src/event/event_processor/processor.rs
crates/walrus-service/src/test_utils.rs
crates/walrus-simtest/src/test_utils.rs
crates/walrus-simtest/tests/simtest_event_blob.rs
crates/walrus-sui/src/client/retry_client/failover.rs
crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs

This PR adds runtime catchup support to the walrus-service event processor so a node that falls behind at runtime can catch up using event blobs, while the checkpoint downloader continues to run safely.
1. Runtime lag monitoring and catchup trigger periodically computes lag between local and network checkpoints which triggers EventBlobCatchupManager when lag exceeds threshold at runtime (not only at startup).
2. New CatchupCoordinationState handles Stop/Restart/CatchupFailed with an unbounded channel.
3. Tailing uses start_tailing_checkpoints_with_restart_support to listen for coordination messages.
4. Processing phase sends a stop message, waits for acks, then restarts tailing afterwards.
5. Added an ack using Notify to signal when checkpoint tailing has fully stopped.
6. Tailing task …

feat: Allow event blob catchup at runtime
