MystenLabs/walrus

- CONTRIBUTING.md
Adds a note about trivial PRs to our CONTRIBUTING.md file:
This is essentially copied from the [Sui repository](https://github.com/MystenLabs/sui/blob/main/CONTRIBUTING.md#important-note).
> chore: add note about trivial PRs to CONTRIBUTING.md

- .editorconfig
- .github/workflows/issues-monitor.yaml
This is essentially a copy of https://github.com/MystenLabs/sui/pull/20907.
> ci: add workflow that adds comment to new issues

- crates/walrus-service/src/node/events.rs
We do not log what error `get_full_checkpoint` fails with which makes it hard to know the exact cause before server stops
> chore: Log error if rest endpoint is unavailable

- Cargo.lock
- Cargo.toml
> ci: Walrus v1.20.0 version bump

- crates/walrus-sdk/src/client/middleware.rs
- crates/walrus-service/src/common/telemetry.rs
> fix: add `_seconds` and `_bytes` suffixes to metrics.

- .github/workflows/attach-binaries-to-release.yml
> ci: add run-time to workflow

- crates/walrus-service/src/node.rs
- crates/walrus-service/src/node/metrics.rs
> feat: export the node's ID as a metric

- crates/walrus-stress/src/generator.rs
This currently is a failure point in antithesis test, where failure injection could cause the transaction to fail.
This PR only adds retry in the initial writes since we still want `write_fresh_blob_with_epochs`, which is used in the
actual write workload, to handle failures.
---
> test: stress client initial write performs extensive retry

- Cargo.lock
- README.md
- contracts/walrus/sources/staking/staking_inner.move
- crates/walrus-orchestrator/src/protocol/target.rs
- crates/walrus-service/bin/deploy.rs
- crates/walrus-service/src/client/error.rs
- crates/walrus-service/src/node/metrics.rs
- crates/walrus-service/src/testbed.rs
- crates/walrus-stress/Cargo.toml
- crates/walrus-stress/src/main.rs
- crates/walrus-sui/src/client.rs
- crates/walrus-sui/src/client/read_client.rs
- crates/walrus-sui/src/client/transaction_builder.rs
- crates/walrus-sui/src/contracts.rs
- crates/walrus-sui/src/types/move_structs.rs
- docker/local-testbed/files/deploy-walrus.sh
- docker/walrus-antithesis/build-test-config-image/docker-compose.yaml
- docker/walrus-antithesis/build-test-config-image/files/deploy-walrus.sh
- docker/walrus-antithesis/build-test-config-image/files/run-staking.sh
- docker/walrus-antithesis/build-test-config-image/pipeline.sh
- docker/walrus-antithesis/build-walrus-image-for-antithesis/Dockerfile
- docker/walrus-antithesis/build-walrus-image-for-antithesis/build.sh
- docker/walrus-antithesis/build-walrus-image-for-antithesis/update_move_toml.sh
- Automate running the antithesis pipeline locally.
- Write a test driver for restaking WAL during antithesis tests.
CI, Manual testing.
No release impact.
> chore: write a test driver for restaking WAL during antithesis tests

- .github/workflows/code.yml
- .github/workflows/scheduled_reports.yml
- .github/workflows/updates.yml
- Cargo.lock
- Cargo.toml
- contracts/subsidies/Move.lock
- contracts/subsidies/Move.toml
- contracts/wal/Move.lock
- contracts/wal/Move.toml
- contracts/wal_exchange/Move.lock
- contracts/wal_exchange/Move.toml
- contracts/walrus/Move.lock
- contracts/walrus/Move.toml
- docker/walrus-antithesis/sui_version.toml
> fix(deps): bump Sui to testnet-v1.46.0

- crates/walrus-proxy/src/histogram_relay.rs
- crates/walrus-service/src/node/blob_retirement_notifier.rs
- docker/walrus-antithesis/build-walrus-image-for-antithesis/Dockerfile
- docker/walrus-orchestrator/Dockerfile
- docker/walrus-proxy/Dockerfile
- docker/walrus-service/Dockerfile
- docker/walrus-service/Dockerfile.walrus-backup
- docker/walrus-stress/Dockerfile
- rust-toolchain.toml
Bump Rust to latest stable release.
> chore: bump Rust to 1.86

- crates/walrus-service/src/node/dbtool.rs
> feat: add option to only output blob size in dbtool metadata command

- crates/walrus-sui/src/client/retry_client.rs
> fix: Reduce logging verbosity of fallback

- crates/walrus-sui/src/config.rs
> fix: check that the provided address is in the wallet

- Cargo.lock
- crates/walrus-sui/Cargo.toml
- crates/walrus-sui/src/client/metrics.rs
- crates/walrus-sui/src/client/retry_client.rs
Track latency and success rate from metrics for primary and fallback endpoints for rpc calls.
---
> feat: Add metrics to track primary and fallback performance

- crates/checkpoint-downloader/src/downloader.rs
This PR enhances the checkpoint lag monitoring system with better error handling, improved logging, and a better recovery mechanism in case of extended failures by:
1. Improving the error handling for checkpoint lag monitoring failures. The system now provides more detailed logging that includes the specific error details, failure counts, and thresholds.
2. Adding a safety mechanism for handling persistent monitoring failures. When the system fails to monitor checkpoint lag for an extended period (10 consecutive failures), it now scales the worker pool to the average of min/max workers. This prevents the system from operating in an unknown state during extended failures and provides a more predictable fallback behavior.
Existing tests
---
> fix: Adjust number of download workers in case of extended failures

- crates/walrus-service/node_config_example.yaml
- crates/walrus-service/src/node/storage/database_config.rs
Increase default block cache size of column families, and allow for users to change certain subset of the db config easily.
---
> feat: Increase default block cache size

- crates/walrus-service/src/node/events/event_blob_writer.rs
When we reset uncertified blobs from db, we should also delete the corresponding blob from filesystem which we don't do today. While this is not a problem, it leaves garbage blobs behind which makes things hard to debug later on. This PR also cleans up the file system during reset.
Existing blob tests
> fix: Delete uncertified blobs from filesystem when resetting

- Cargo.lock
- Cargo.toml
> ci: Walrus v1.21.0 Version Bump

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- contracts/walrus/sources/staking/active_set.move
- contracts/walrus/tests/staking/staking_inner_tests.move
- updates to `prettier-move@0.3.0` 
- if expression has now slightly different treatment - will try to single line if fits, unless there's a reason to break, or a block
---
> chore(fmt): uses fresher build of the formatter

- crates/walrus-sui/src/client/retry_client.rs
> fix: Fix the checkpoint height computation

- .github/workflows/attach-binaries-to-release.yml
- .github/workflows/code.yml
- .github/workflows/publish-docs.yaml
- .github/workflows/scheduled_reports.yml
- .github/workflows/update-ws-binaries.yaml
- .github/workflows/updates.yml
Switch to a new ubuntu-ghcloud-2 runner
👀
> ci: Switch to a new ubuntu-ghcloud-2 runner

- .github/workflows/code.yml
- crates/walrus-sui/src/client/retry_client.rs
Installing openssl for builds
Making sure CI passes on the PR
> fix: Installing openssl for builds

- .github/workflows/code.yml
- crates/walrus-sui/src/client/retry_client.rs
Cherry pick the https://github.com/MystenLabs/walrus/pull/1909
---
> fix: Cherry pick change to fix fallback on NotFound error

- .github/workflows/code.yml
- crates/walrus-service/src/node.rs
> fix: ci build

- crates/walrus-service/node_config_example.yaml
- crates/walrus-service/src/node/config.rs
This increases several default parameters for shard transfer and recovery to make it more peformant.
Most of these parameters were already tested in the recent epoch change on Mainnet.
---
> fix(node): adjust default params for shard sync

- crates/walrus-service/src/client/metrics.rs
Causing node crashing in CI
---
> fix: histogram bucket def

- crates/walrus-service/src/node/dbtool.rs
- crates/walrus-service/src/node/events/event_processor.rs
> feat: Add db tool command to print init state

- Cargo.lock
- Cargo.toml
> ci: Walrus v1.22.0 version bump

- crates/walrus-sui/src/client/retry_client.rs
Allow with_failover to support all retriable error types.
CI Pipeline.
> chore: widen the compile-time interface of with_failover

- crates/walrus-service/src/client/cli/args.rs
- docs/book/SUMMARY.md
- docs/book/operator-guide/aggregator.md
- docs/book/operator-guide/auth-publisher.md
> docs: add docs on the authenticated publisher

- Cargo.toml
- crates/walrus-service/src/client/daemon.rs
- crates/walrus-service/src/client/daemon/routes.rs
- crates/walrus-service/src/node/server.rs
- deny.toml
* chore: upgrade tokio
* fix: add CORS headers to server endponints
* fix: ordering and method headers
---------
---
> fix: cherry pick add CORS headers to server endponints (#1953)

- contracts/README.md
- contracts/subsidies/sources/subsidies.move
- contracts/walrus/sources/staking.move
- contracts/walrus/sources/system.move
- crates/walrus-e2e-tests/tests/test_client.rs
- crates/walrus-e2e-tests/tests/test_event_blobs.rs
- crates/walrus-service/src/test_utils.rs
- crates/walrus-service/tests/epoch_change.rs
- crates/walrus-simtest/tests/simtest.rs
- crates/walrus-simtest/tests/simtest_event_blob.rs
- crates/walrus-simtest/tests/simtest_failure.rs
- crates/walrus-simtest/tests/simtest_param_sync.rs
- crates/walrus-sui/src/system_setup.rs
- crates/walrus-sui/src/test_utils/system_setup.rs
- crates/walrus-sui/tests/test_walrus_sui.rs
closes WAL-653
closes WAL-654
- existing tests
- PR modifies the upgrade test to actually test the upgrade from the previous contract version to the development version
---
> test: test contract upgrades from previous contract version

- .github/workflows/attach-binaries-to-release.yml
- .github/workflows/create-release.yml
Fix attaching binaries to new releases
👀
> ci: Fix attaching binaries to new releases

- .github/workflows/attach-binaries-to-release.yml
> ci: use ref_name

- .github/workflows/lint.yml
- crates/walrus-utils/src/lib.rs
Add a debugging helper macro for logging.
CI.
> chore: add a "crumb" macro to walrus_utils for help in debugging

- crates/walrus-sui/src/client.rs
- crates/walrus-sui/src/client/transaction_builder.rs
> feat: optimize call to reserve storage for multiple blobs

- .gitignore
- crates/walrus-core/src/messages.rs
- crates/walrus-core/src/messages/certificate.rs
- crates/walrus-sui/Cargo.toml
- crates/walrus-sui/benches/gas_cost_bench.rs
- crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs
- crates/walrus-sui/src/lib.rs
- crates/walrus-sui/src/test_utils.rs
- crates/walrus-sui/src/test_utils/system_setup.rs
- crates/walrus-sui/src/types.rs
- crates/walrus-sui/src/types/move_structs.rs
- crates/walrus-sui/src/utils.rs
- crates/walrus-sui/tests/test_walrus_sui.rs
- scripts/plot_contract_cost.py
Adds a benchmark to evaluate the gas cost for calls to reserve & register blobs and to certify them.
ran benchmark
---
> chore: add gas cost benchmark for contracts

- docs/book/operator-guide/aggregator.md
Added docs with more publisher options following discussions with Walrus users.
Proof read.
> docs: Added some more docs for publisher

- CONTRIBUTING.md
- Add a note about discussing an issue before creating PRs.
- Fix the instructions for integration tests.
- Temporarily remove mention of tarpaulin until it is fixed.
None.
> docs: improvements in CONTRIBUTING.md

- .rustfmt.toml
- Cargo.toml
- crates/walrus-sdk/src/config/committees_refresh_config.rs
- crates/walrus-service/src/backup/service.rs
- crates/walrus-service/src/node.rs
- crates/walrus-service/src/node/committee/committee_service.rs
- crates/walrus-service/src/node/contract_service.rs
- crates/walrus-service/src/node/epoch_change_driver.rs
- crates/walrus-service/src/node/storage.rs
- crates/walrus-stress/src/generator.rs
- crates/walrus-stress/src/generator/blob.rs
- crates/walrus-sui/src/client/retry_client/retriable_rpc_client.rs
- crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs
- crates/walrus-test-utils/src/lib.rs
Upgrade to Rust Edition 2024.
CI Pipeline.
> chore: upgrade to rust edition 2024

- Cargo.lock
- crates/walrus-sdk/src/config.rs
- crates/walrus-sdk/src/utils.rs
- crates/walrus-service/bin/backup.rs
- crates/walrus-service/bin/deploy.rs
- crates/walrus-service/bin/node.rs
- crates/walrus-service/src/common/utils.rs
- crates/walrus-service/src/node/config_synchronizer.rs
- crates/walrus-stress/src/main.rs
- crates/walrus-utils/Cargo.toml
- crates/walrus-utils/src/lib.rs
Move load_from_yaml into walrus_utils.
CI Pipeline.
> refactor: move load_from_yaml in to walrus_utils

- Cargo.lock
- Cargo.toml
> ci: Walrus v1.24.0 Version Bump

- .github/workflows/publish-docs.yaml
- .github/workflows/update-ws-binaries.yaml
The site-builder has been improved recently, this PR reflects these changes in our GH workflows.
Run the workflows.
> ci: update WS workflows with new site-builder functionality

- crates/walrus-sui/benches/gas_cost_bench.rs
- scripts/plot_contract_cost.py
Improves the gas cost benchmark to allow updating the gas price when analyzing the benchmark output.
Manually ran benchmark
---
> chore: include gas price in gas cost benchmark

- Cargo.lock
- crates/checkpoint-downloader/Cargo.toml
- crates/checkpoint-downloader/src/downloader.rs
- crates/checkpoint-downloader/src/lib.rs
- crates/walrus-simtest/tests/simtest_failure.rs
> fix: fix deadlock when creating checkpoint downloader when lag is high

- crates/checkpoint-downloader/src/downloader.rs
- crates/walrus-service/src/common/utils.rs
- crates/walrus-service/src/node/events/event_processor.rs
- crates/walrus-sui/src/client/retry_client/retriable_rpc_client.rs
Some of the metrics are not tracked.
---
> chore: initialize metrics in RetriableRpcClient and mysten_metrics

- Cargo.lock
- Cargo.toml
> ci: Walrus v1.25.0 Version Bump

- crates/walrus-sdk/src/client.rs
While responding to a failure in the publisher, I was reading the logs for the aggregator and couldn't tell whether the forced committee refresh was succeeding or not. Enhance logging around force_refresh_committees. 
CI Pipeline.
> chore: enhance logging around Client::force_refresh_committees

- crates/walrus-service/src/common/utils.rs
> fix: cherry-pick remove mysten_metrics initialization

- .github/actions/diffs/action.yml
- .github/workflows/code.yml
Similar to other such warnings added in #1391 and #1482.
CI.
> ci: add warning to PRs that modify the CLI

- .github/workflows/code.yml
- .github/workflows/scheduled_reports.yml
- .github/workflows/updates.yml
- Cargo.lock
- Cargo.toml
- contracts/subsidies/Move.lock
- contracts/subsidies/Move.toml
- contracts/wal/Move.lock
- contracts/wal/Move.toml
- contracts/wal_exchange/Move.lock
- contracts/wal_exchange/Move.toml
- contracts/walrus/Move.lock
- contracts/walrus/Move.toml
- crates/typed-store/Cargo.toml
- crates/typed-store/src/rocks.rs
- docker/walrus-antithesis/sui_version.toml
Bump Sui and its necessary dependencies to v1.48.0.
CI Pipeline.
> chore: bump version of all Sui dependencies to v1.48.0 testnet release

- Cargo.lock
- Cargo.toml
> ci: Walrus v1.26.0 version bump

- crates/walrus-service/src/node/consistency_check.rs
> feat: make sampled blob selection deterministic based on epoch in sliver consistency check

- crates/walrus-sui/src/client/retry_client/retriable_rpc_client.rs
Ran with seed search and ran the test.
```
./scripts/simtest/seed-search.py --num-seeds 50 --concurrency 5 --seed-start 57832 --test simtest_event_blob test_checkpoint_downloader_with_additional_fullnodes
All tests passed successfully!
```
---
> fix: Add timeout to the call checking for rest endpoint

- .github/workflows/create-release-announce.yml
automate Walrus release creation
Will test after this lands
> ci: automate release creation

- crates/walrus-sdk/src/client/client_types.rs
This should not change any business logic, just improve the logging behavior with DEBUG logging enabled:
- Correctly set uninitialized field to `field::Empty`.
- Use `span.in_scope` instead of calling `enter()`.
- Avoid logging huge amounts of data.
- Deduplicate some code with new `log_state` function.
- Some other minor refactoring.
Automatic tests + some manual testing:
```terminal
$ echo 'Hello Walrus!' > hello
$ export RUST_LOG=info,walrus=info,walrus_sdk::client::client_types=debug          
$ target/debug/walrus --context testnet store --epochs 1 hello
2025-05-16T15:35:56.515849Z  INFO walrus: client version: 1.26.0-611147f2b97d-dirty
2025-05-16T15:35:56.516962Z  INFO walrus_sdk::config: using Walrus configuration from '~/.config/walrus/client_config.yaml' with 'testnet' context …
```
> fix(client): improve debug logging for store

- testnet-contracts/subsidies/Move.lock
- testnet-contracts/subsidies/sources/subsidies.move
- testnet-contracts/subsidies/tests/subsidies_tests.move
Updates `testnet-contracts/subsidies` to the newest deployed version.
Manually tested after deployment.
---
> chore: upgrade subsidies testnet contracts

- crates/walrus-service/src/node/events/event_processor.rs
This PR handles the scenario when `get_latest_checkpoint_summary` is unavailable because all full node endpoints are down. But `get_checkpoint_summary` still works because archival is working. We fallback to catchup using event blobs in such a scenario.
---
> fix: Handle event processor bootstrap when latest checkpoint is unavailable

- crates/walrus-service/src/node/storage/blob_info.rs
> test: add more tests for the blob info table

- crates/walrus-sdk/src/client.rs
Closes WAL-673
Before this PR, the aggregator kept refreshing the committee and retrying to get the blob for a long time (anecdotally, up to ~50s) for non-existent blobs. This was because there is no explicit way to distinguish between the blob not being stored because (i) it does not exist, vs (ii) it exists but we are under expoch change and we are asking the wrong committee.
This PR forces a status check on the blobs being read. This adds a tiny bit of latency in the case the blob exists (i.e., 1 rtt to the nodes to get the status), but allows to fail much earlier if the blob does not (~0.1 s vs tens of seconds).
The PR also reduces the level of warnings related to retries to avoid noise in the common case.
Manual aggregator queries + existing tests.
---
Check each box that your …
> fix(aggregator): fail early for inexistent blobs

- crates/walrus-e2e-tests/tests/test_client.rs
- crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs
- crates/walrus-sui/src/utils.rs
Fixes issue found in Antithesis run regarding polling a dead stream.
CI Pipeline.
> fix: avoid complex logic in select_coins_with_limit

- crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs
Simplifies the `select_coins_with_limit` function to make it easier to understand.
existing tests
---
> fix: simplify select_coins_with_limit

- crates/walrus-service/src/node/storage/database_config.rs
> feat: [cherry-pick] add options to update compaction write throttling, and set high write stalling threshold in metadata table

- .github/workflows/create-release-announce.yml
fix getting release announce
https://github.com/MystenLabs/walrus/actions/runs/15199087741
> ci: fix getting release announce

- Cargo.lock
- Cargo.toml
> ci: Walrus v1.27.0 Version Bump

- crates/walrus-service/src/node.rs
* Add tokio metrics for event polling
* also record queuing blob sync latency
* instrument sliver existence check
* Address comments
---
> feat: [cherry-pick] instrument event stream polling with tokio metrics (#2129)

- CONTRIBUTING.md
Update CONTRIBUTING.md to teach folks how to configure `.vscode/settings.json`.
View file.
> chore: add to CONTRIBUTING

- crates/walrus-e2e-tests/tests/test_client.rs
wait until blob is certified and then read
---
> fix: address flaky test_blocklist

- CONTRIBUTING.md
Describe various conventions we (mostly) follow in our codebase in the `CONTRIBUTING.md` file.
Not needed.
> docs: describe coding conventions

- .github/workflows/attach-binaries-to-release.yml
Fix Windows nexttest installation
https://github.com/MystenLabs/walrus/actions/runs/15425254220/job/43410413809
> ci: fix windows nexttest installation

- mainnet-contracts/subsidies/sources/subsidies.move
- mainnet-contracts/walrus/Move.lock
Upgrades the subsidies contract on mainnet.
Workflow run to create the unsigned Tx for the multisig is [here](https://github.com/MystenLabs/walrus/actions/runs/15420448891).
Transaction upgrading the contract: [Fjn3dKFwVEBfgQgWsZCKMMnBP1JLGR5kXK3yPV1xAE2o](https://suiscan.xyz/mainnet/tx/Fjn3dKFwVEBfgQgWsZCKMMnBP1JLGR5kXK3yPV1xAE2o)
Has been running on testnet.
---
> chore: mainnet upgrade for subsidies contract

- crates/walrus-service/src/node/node_recovery.rs
The functionality of rate limiting concurrent blob sync can be achieved via monitoring ongoing_sync length.
---
> chore: remove redundant semaphore used in node recovery

- .github/workflows/create-release-announce.yml
- .github/workflows/lint.yml
- .github/workflows/update-operators-cache.yml
- .pre-commit-config.yaml
- .yamlfmt.yml
Update yamlfmt to latest version and use same version in CI and pre-commit.
Not needed.
> chore: update yamlfmt and use same version in CI

- Cargo.lock
- crates/walrus-service/src/node/node_recovery.rs
- crates/walrus-simtest/tests/simtest_failure.rs
Adds the missing tests for the fix in #2179.
Added in this PR.
> test: add test coverage of node restart during recovery

- crates/walrus-service/node_config_example.yaml
- crates/walrus-service/src/node.rs
- crates/walrus-service/src/node/blob_event_processor.rs
- crates/walrus-service/src/node/config.rs
- crates/walrus-service/src/node/metrics.rs
- crates/walrus-service/src/test_utils.rs
- crates/walrus-service/src/testbed.rs
- crates/walrus-simtest/src/test_utils.rs
- crates/walrus-simtest/tests/simtest.rs
- crates/walrus-simtest/tests/simtest_failure.rs
* non-blocking event processing
* Add config to config number of workers; add blob deletion workload; add tests
* Add documentation
* fix tests
* Address comments
---
> feat: [cherry pick (#2177)] non-blocking event processing 

- Cargo.lock
- Cargo.toml
> ci: 1.28 version bump

- .github/workflows/code.yml
- .github/workflows/scheduled_reports.yml
- .github/workflows/updates.yml
- Cargo.lock
- Cargo.toml
- contracts/subsidies/Move.lock
- contracts/subsidies/Move.toml
- contracts/wal/Move.toml
- contracts/wal_exchange/Move.toml
- contracts/walrus/Move.toml
- crates/checkpoint-downloader/src/downloader.rs
- crates/typed-store/src/rocks/tests.rs
- crates/walrus-orchestrator/src/settings.rs
- crates/walrus-service/src/node.rs
- crates/walrus-service/src/node/events/event_blob_writer.rs
- crates/walrus-service/src/node/events/event_processor.rs
- crates/walrus-sui/src/client/retry_client/retriable_sui_client.rs
- crates/walrus-sui/src/system_setup.rs
- docker/walrus-antithesis/sui_version.toml
- scripts/simtest/cargo-simtest
* chore: bump sui version to testnet-v1.50.1
> chore: bump sui version to testnet-v1.50.1 (#2196)

- crates/walrus-sui/src/client/metrics.rs
> fix: Rename the metric label to prevent conflict

- crates/walrus-service/src/client/cli/args.rs
- crates/walrus-service/src/client/cli/cli_output.rs
- crates/walrus-service/src/client/cli/runner.rs
- crates/walrus-service/src/client/responses.rs
* Improve error handling.
* Make number of concurrent requests configurable and increase the default.
* Some minor refactoring.
Run the command.
> fix(client): minor improvements to the health command

- crates/walrus-service/src/node.rs
- crates/walrus-service/src/node/blob_sync.rs
This PR fix a race condition between a node entering recovery mode due to lagging too far behind, and start of blob sync.
The specific sequence of the race condition is follows:
- Blob sync starts, checking the node is in Active state. Blob sync starts async task `A` to sync blob.
- Node enter recovery mode.
- task `A` starts. Because the node is lagging too far behind (the committee read by the node just now is too far ahead), the node does not know the shard assignment for the event epoch, therefore a panic is triggered.
The fix contains two parts:
- When a node enters recovery mode, it needs to cancel all ongoing blob syncs since once the node catches up to the latest epoch, it'll scan all the certified blobs and recovery any missing blobs
- However, the above is not enough because …
> fix: race condition between node entering recovery mode and start blob sync

- crates/typed-store/src/rocks.rs
- crates/walrus-service/node_config_example.yaml
- crates/walrus-service/src/node/storage/database_config.rs
- Turn on bloom filter
- Increase block size
- Use large block cache in sliver CFs.
---
> feat: DB tuning

- crates/walrus-service/node_config_example.yaml
- crates/walrus-service/src/common/telemetry.rs
- crates/walrus-service/src/node/config.rs
- crates/walrus-service/src/node/server.rs
- crates/walrus-service/src/node/server/routes.rs
cherry-pick #2214 #2215 #2225 to 1.27
---
> chore: cherry pick a few blob recovery configuration tuning

- crates/walrus-storage-node-client/src/client/middleware.rs
> fix: observe_response_body_size records to response_body_size_bytes

- crates/walrus-service/src/node/recovery_symbol_service.rs
This PR moves symbol creation to a blocking thread where it joins the proof creation. Tt was causing a lot of blocking on the tokio core thread. This was always the case, but the current amount of recovery on mainnet highlighted it as an issue.
Load tested using k6. The average slow poll duration for GET recoverySymbols is now lower, and it is now able to accept a large amount of requests and saturate the CPU before saturating the tokio core threads.
---
a user might notice and any actions they must take to implement updates. (Add release notes after the …
> fix: move the creation of the recovery symbol to a blocking thread

- crates/walrus-service/src/node/config.rs
> fix: add serde default in Http2Config

- .github/workflows/code.yml
- .github/workflows/scheduled_reports.yml
- .github/workflows/updates.yml
- Cargo.lock
- Cargo.toml
- contracts/subsidies/Move.lock
- contracts/subsidies/Move.toml
- contracts/wal/Move.lock
- contracts/wal/Move.toml
- contracts/wal_exchange/Move.lock
- contracts/wal_exchange/Move.toml
- contracts/walrus/Move.lock
- contracts/walrus/Move.toml
- contracts/walrus_subsidies/Move.lock
- contracts/walrus_subsidies/Move.toml
- docker/walrus-antithesis/sui_version.toml
> chore: bump sui to v1.51.1

- crates/walrus-service/src/node.rs
- crates/walrus-service/src/node/storage/shard.rs
Found this leftover TODO branch locally.
---
> test: check that shard sync progress is cleared after sync finishes

- .editorconfig
- docker/walrus-antithesis/build-test-config-image/Dockerfile
- docker/walrus-antithesis/build-walrus-image-for-antithesis/Dockerfile
- docker/walrus-orchestrator/Dockerfile
- docker/walrus-service/Dockerfile
- docker/walrus-service/Dockerfile.walrus-backup
- docker/walrus-stress/Dockerfile
> chore: use internal registry for Docker image

- crates/walrus-service/src/event/event_processor/catchup.rs
The PR fixes the call by passing ending checkpoint instead of ending index.
---
> fix: Pass ending blob checkpoint instead of event index

- docker/walrus-antithesis/build-test-config-image/Dockerfile
- docker/walrus-antithesis/build-walrus-image-for-antithesis/Dockerfile
> chore: antithesis image should use public image

- crates/walrus-simtest/src/test_utils.rs
- crates/walrus-simtest/tests/simtest_event_blob.rs
- crates/walrus-simtest/tests/simtest_failure.rs
This test doesn't really test event blob interaction, and more of testing fullnode failure scenario.
---
> chore: move test_checkpoint_downloader_with_additional_fullnodes to simtest_failure test target

- crates/checkpoint-downloader/src/downloader.rs
- crates/walrus-service/src/node.rs
- crates/walrus-service/src/node/blob_event_processor.rs
monitor scope preserve scope
---
> fix: [cherry-pick] monitor scope preserve scope (#2295)

- .github/workflows/update-ws-install.yaml
Fixes a minor oversight in #2299.
See [this workflow run](https://github.com/MystenLabs/walrus/actions/runs/16174908571).
> ci: fix quotes in update-ws-install.yaml

- crates/walrus-service/src/event/event_blob_downloader.rs
- crates/walrus-service/src/event/event_processor/catchup.rs
- crates/walrus-service/src/event/event_processor/processor.rs
- crates/walrus-service/src/node.rs
Was helpful (to me) to investigate init cursor mismatch
---
> chore: adding some logs around cursor initialization

- Cargo.lock
- Cargo.toml
- crates/walrus-service/src/node/dbtool.rs
> fix(dbtool): [cherry-pick] fix drop column family command

- crates/walrus-service/src/node.rs
Caught in simtest that if the first event is epoch change start event, we currently set the node's latest_event_epoch`
to the epoch change event, which hasn't been executed yet. If any blob sync is started before the epoch change
finishes, the sync won't be able to get the epoch shard assignment, since it is still unknown.
The fix is to set the `latest_event_epoch` to the previous epoch, if the first epoch is an epoch change start event.
100 simtest run
---
a user might notice and any actions they must take to implement updates. (Add release notes after the …
> fix: set initial `latest_event_epoch` if first event is epoch change

- docs/theme/head.hbs
Adds Algolia site verification to allow crawling.
local
---
> chore: add Algolia site verification

- crates/walrus-service/src/node/blob_sync.rs
Cherry-picks #2365.
Deployment to Testnet.
> fix: reduce excessive logs around cancelling blob syncs (cherry-pick)

- docs/book/assets/operators.json
Added H2O Nodes aggregator and publisher
aggregator.walrus-testnet.h2o-nodes.com
publisher.walrus-testnet.h2o-nodes.com
aggregator.walrus-mainnet.h2o-nodes.com
> docs: add H2O Nodes aggregator and publisher

- crates/walrus-simtest/tests/simtest.rs
> chore: remove simtest compilation warning

- Cargo.lock
- Cargo.toml
Walrus `v1.31.0` Version Bump
👀
> ci: Walrus `v1.31.0` Version Bump

- crates/walrus-sui/src/client/read_client.rs
- crates/walrus-sui/src/types/move_structs.rs
> chore: clean up no-longer-needed `SystemStateInnerV1Testnet`

- crates/walrus-sui/src/client/retry_client/retriable_rpc_error.rs
* fix(client): add HTML error codes to retriable RPC errors
* Update crates/walrus-sui/src/client/retry_client/retriable_rpc_error.rs
---------
---
> fix(client): add HTML error codes to retriable RPC errors (#2411)

- .github/actions/diffs/action.yml
- .github/workflows/code.yml
- .licensesnipignore
- .pre-commit-config.yaml
- scripts/move_tests.sh
See https://github.com/MystenLabs/walrus/pull/2392#discussion_r2245167283 for context.
CI.
> chore: improve setup for Move tests and coverage

- docker/walrus-antithesis/build-walrus-image-for-antithesis/Dockerfile
- docker/walrus-orchestrator/Dockerfile
- docker/walrus-proxy/Dockerfile
- docker/walrus-service/Dockerfile
- docker/walrus-service/Dockerfile.walrus-backup
- docker/walrus-stress/Dockerfile
- docker/walrus-upload-relay/Dockerfile
> chore: bump Rust version in Dockerfiles to 1.89

- .github/workflows/gen-sui-upgrade-version-pr.yml
Add a workflow to create sui testnet upgrade PR
Will be testing and finalizing this PR once it lands
> ci: add workflow to create sui testnet upgrade PR

- .github/workflows/gen-sui-upgrade-version-pr.yml
add repo dispatch to pr gen
Depeneds on https://github.com/MystenLabs/sui/pull/23275
👀
> chore: add repo dispatch to pr gen

- scripts/bump_sui_testnet_version.sh
set version bump pr to auto-merge
👀
> chore: set version bump pr to auto-merge

- scripts/bump_sui_testnet_version.sh
Reverts MystenLabs/walrus#2482
> ci: Revert "chore: set version bump pr to auto-merge"

- .github/workflows/attach-binaries-to-release.yml
Skip building binaries if they were already built for the previous network. 
https://github.com/MystenLabs/walrus/actions/runs/17473435843/job/49627290174
> chore: skip building binaries if they were already built

- crates/typed-store/src/rocks.rs
- crates/typed-store/src/rocks/errors.rs
- crates/typed-store/src/rocks/tests.rs
- crates/typed-store/src/traits.rs
- crates/walrus-service/src/event/event_processor/processor.rs
- crates/walrus-service/src/node/db_checkpoint.rs
This PR adds the ability to do optimistic transactions with commit/rollback semantics and conflict handling with retry logic. Includes minor test helpers and fixes to existing tests.  The current functionality does not change.
Added some unit tests.
> feat: Add transaction support in typed-store

- contracts/walrus/sources/display.move
- contracts/walrus/sources/init.move
- contracts/walrus/sources/staking/committee.move
- contracts/walrus/sources/system/event_blob.move
- contracts/walrus/sources/utils/sort.move
- contracts/walrus_subsidies/sources/walrus_subsidies.move
Complaining since upgraded to sui 1.55
---
> chore: apply move lint suggestions

- scripts/k6/src/tests/aggregator/aggregator_v1_get_blobs_breakpoint.ts
- scripts/k6/src/tests/publisher/publisher_v1_put_blobs_breakpoint.ts
> fix: increase setup timeout

- crates/walrus-service/node_config_example.yaml
- crates/walrus-service/src/node/config.rs
- crates/walrus-service/src/node/storage/shard.rs
- crates/walrus-service/src/test_utils.rs
I think it may miss the last flush. @sadhansood can you PTAL and confirm?
---
> chore: turn off sst injection by default

- CONTRIBUTING.md
- Cargo.toml
- crates/walrus-core/src/encoding/basic_encoding.rs
- crates/walrus-core/src/encoding/blob_encoding.rs
- crates/walrus-core/src/encoding/config.rs
This is a cherry-pick of #2549.
See #2549.
---
> fix(core): optimize memory allocations during blob decoding

- crates/typed-store/src/metrics.rs
- crates/typed-store/src/rocks.rs
- crates/typed-store/src/rocks/tests.rs
- crates/walrus-service/src/node/storage/shard.rs
> chore(cherrypick): group per shard histogram metrics by column family class instead of column family name (#2590)
